### ISSUE TITLE
ModelEditor - zpracování yaml errorů

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#10]
- poslední validní soubor bude v good_version proměnný
- v případě že dojde při parsrování yamlu k chybě, dojde k identifikaci chybných bloků porovnáním s předchozí good_version, a k identifikaci (podle identation a párových víceřádkových tagů) a uložení chybných bloků do error_remainder[]
- chybné bloky zkusíme vrátit po jednom do good_version, tím vznikne nová good_version a error_remainder[]
- error_remainder[] se transformuje do errors

**Comment by sha512rp** [comment]
Aktualne se detekuji parsing errory a vsechny zmeny jsou ignorovany az do opraveni erroru.

**Comment by richtertul** [comment]
Pokud by si měl dojem že celkové selhání struktury je ojedinělé, možná by jsi mohl vyspecifikovat 2-3 scénáře kdy k němu dochází a nechat to jak to je. Možná by dalšímu postupu měla předcházet analýza těchto scénářů.
