### ISSUE TITLE
Job Scheduler - projekt do analyzis

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#105]
- Přejmenovat projekt na analyzis
- sloučit edit a předidat do edit jak možnost vybírat yamly, tak přidávat cesty k externím souborům (duplicitní funkcionalita může být i v model editoru)
- při vytváření mj přidat volbu analyzis (bez ohledu na to co je vybráno)
- nakopírovat aktuální analyzis a externí soubory do jobs

**Comment by jbrezmorf** [comment]
Slouceni projektu a analysis ANO.

**Comment by richtertul** [comment]
Dokud nebude geomop applikace, potřebujeme mít analzyis i v model editoru, kvůli sdílení parametrů. Pak dořešíme její odstranění z Model Editoru.

**Comment by tomaskrizek** [comment]
Slouceno do jednoho. Musel jsem zmenit spoustu veci a nemel jsem jeste cas to otestovat. Je mozne, ze jsem nekde neco zapomnel prejmenovat. Asi bude opet potreba smazat konfiguraky a projektove/analysis soubory.

K pridavani externich souboru jsem se taky jeste nedostal, ale to taky potrebuju jeste trochu upresnit.

**Comment by tomaskrizek** [comment]
Vyber meshu(souboru) dodelan.
