### ISSUE TITLE
Job Scheduler - Pojmenování mj

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#106]
Při vytváření multijobu se bude vybírat analysis a bude nabídnuto jméno multijobu ve tvaru:
`<resource name>_<counter>`.  Jméno multijobu bude jedinečné v rámci analysis a jeho identifikátorem bude `analyzis_name + "_" +mj_name` (napr. pro docasne adresáře). Projekt se také zobrazí v listu mj před. 

Po vytvoření multijobu se vytvoří v analysis mj adresář, převezme aktuální analyzis a nakopíruje ji (pouze malé soubory) do mj adresáře. (stávající mj adresáře budou sloužit i pro určení jména mj, které se má nabídnout)... JB: raději counter v analysis
PR: Zatím kopírujem vše, nutno vymyslet jak zacházet se změnanama velkých souborů a jejich porovnávání. (Zatím přidáváme hash, ale co když došlo ke změně souboru mezi definicí mj a spuštěním, mám vzít nový soubor?)

... je nutne aby kompletni info o MJ bylo v  jeho docasnem adresari. MJ na remote, ktera nebudou mit 
MJ adresar na klientovi se budou ignorovat (pripadne mazat, pripadne do budoucna nabidka rekonstrukce).

~~Do multijob menu přibyde položka Chage Analzyis, která pro multijob v jiném stavu než finished umožní měnit analyzis. (JESTE rozmyslet)~~

**Comment by tomaskrizek** [comment]
Nazvy multijobu predelany. Analysis se prekopiruje pri vytvoreni mj (vsechny vybrane soubory bez ohledu na velikost) do adresare daneho mj.
