### ISSUE TITLE
Job Scheduler - Vylepšení stavů 

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#107]
Do mj listu jsem přidal i chybový stav. Bylo by dobré nějakým způsobem (např. status bar, bublinková nápověda po volbě, nebo najetí kurzoru) zobrazit chybovou hlášku jak u mj, tak jobu v chybovém stavu. Pokud bude v chybovém stavu nějaký job, přepíše se do chybového stavu i mj s hláškou, že nedoběhli všechny joby. 

-Chybový stav přidám do proměnné error v ui.data.mj_data.MultiJob (bude pro stavy error a no-response)
-Zvážit přidání ikonek, nebo podbarvit položky listů.

**Comment by richtertul** [comment]
Honza: zdokumentování existujicich stavu a jejich významu. Pro MJ rozlišit error v jobu a jeho vlastní error, možná na to mít odlišné stavy.

**Comment by tomaskrizek** [comment]
Pridano podbarveni pro `TaskStatus.error` + zobrazeni zpravy do status baru po kliknuti na mj.

Asi by to chtelo i nejaky dalsi stav, `TaksStatus.job_error`, ktery by signalizoval, ze doslo k chybe v jobu. 

Je mozne barevne rozlisit `error`, `interrupted` (No response) a pripadne `job_error`. Pro error jsem zvolil svetle cervenou, ostatni jsem zatim nechal bez podbarveni.

Kontrolu, zda vsechny joby probehly musim jeste dodelat, budu to delat spolecne s prevedenim jobu do stavu finished - ale na tom se jeste potrebuju domluvit.

**Comment by tomaskrizek** [comment]
Vyreseno. Pridana kontrola provedeni jobu po prechodu mj do stavu finished. Joby, ktere skonci chybou jsou take podbarveny.
