### ISSUE TITLE
Job Scheduler - kopírování výsledků

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#108]
Po úspěšném dokončení mj se automaticky nakopírují výsledky, senam jobu a logy do mj adresáře v projektu.

Pro ukonceni MJ bude umožněna pouze akce copy a delete.

DOMYSLET:
Dojde také k smazání adresáře v prozatimním  job scheduler adresáři  a zobrazované výsledky se budou načítat z projektového adresáře. Delete upozorní a následně smaže mj adresář v projektu.

**Comment by jbrezmorf** [comment]
Všechna data MJ budou v podadresáři analysis, tam se též stáhnou výsledky a tam vše také zůstane.
Pokud bychom chtěli nedokončené MJ oddělit dal bych je v rámci analysis do podadresáře "processing" a pak pouze přesunul o úroveň výše.

**Comment by richtertul** [comment]
Jinná logika
