### ISSUE TITLE
přidání tagů

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#11]
- typ abstraktní proměnné bude v tagu
- reference bude označena tagem REF

**Comment by sha512rp** [comment]
podpora tagu a referenci pridana v a5a575a865c7d7a91ca08dc44c1a03b7d404d189
pro reference jsem pouzil !ref (case-sensitive), pripadne to muzeme upravit, ale lowercase mi prijde lepsi

**Comment by richtertul** [comment]
Za mě je to jedno
