### ISSUE TITLE
Job Scheduler + Model Editor - prokliky

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#110]
Měli by být prokliky:

1. Zobrazit soubor z Analzyis v model editoru
2. Umožnit otevřít JobScheduler s aktuálním projektem.
3. ??? Umět otevřít další soubor v novém okně
Poznámky:

  - U job scheduleru by měla být vždy jen jedna instance, která se při prokliku vytvoří/otevře a vní se otevře odpovídající analysis
  - Navrhuji to dělat přes popen, kterému se předá spustitelný soubor a parametry
  - U model editoru by parametry měli umožnit zadat soubor a projekt, job scheduleru projekt a v případě zadaného projektu otevřít analysis dialog.

**Comment by jbrezmorf** [comment]
Posledni bod: domyslet roli ModelEditoru, budto samostatny editor YAMl souboru (nevi nic o projektech, analysis a pod.) nebo integrovana aplikace, kde je aktualni jeden projekt napric komponentami (kontexty).

**Comment by richtertul** [comment]
bude se dělat jiná logika
