### ISSUE TITLE
Job Scheduler - zobrazování výsledků

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#111]
- textové - mě to pořád blbne a myslím že by qt editor byl lepší, v případě logů by se možná dalo vymyslet i něco lepšího

**Comment by jbrezmorf** [comment]
- QT editor pro rychle zobrazeni texovych dat vhodny, ostani nechat na uivateli
- vytvorit nastroj pro export nastaveni multijobu, pro efektivni reportovani problemu:
nastaveni + vsechny logy zalohovat pres tlacitko Save results& logs

**Comment by richtertul** [comment]
Jen textový editor, pokud by to bylo málo práce, mě to ušetří hodně času.
