### ISSUE TITLE
Job Scheduler - oddělit nastavení jobu pro pbs 

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#114]
Domyslet pbs settings, jde o to co by vlastně měl nastavovat uživatel a co applikace a jak se postavit k mj_service v pbs (Je zde možné zadat ji jako zvláštní pbs nastavení, tím však probublá tato volba do nastavení resources, které by mohl chtít nastavovat i uživatel.).

**Comment by jbrezmorf** [comment]
Nerozumím.
