### ISSUE TITLE
Model Editor - konverze

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#115]
Zkontrolovat, napsat testy a možná dospecifikovat a upravit konverzi, která vyplynula z testování.

**Comment by tomaskrizek** [comment]
S tim Abstractem jsem pri implementaci nepocital. Pavlova uprava funguje, ale vznika tam jedno omezeni. Vsechny klice dane implementace **musi** byt skalary. Pro vsechny implementace `Field:R3 -> R` tomu tak je, takze to funguje.

@jbrezmorf Pokud by se do budoucna pocitalo s tim, ze *v klicich* implementaci Abstractu, nad kterymi se provadi transpozice, *muze byt i pole nebo zaznam*, musel bych to predelat. Bohuzel by to nebyla uplne jednoducha zmena, asi by mi to den nebo dva zabralo.

**Comment by tomaskrizek** [comment]
Pri testovani jsem narazil na dalsi problemy, ktere zpusobuje uprava transpozice:
- chyby typu #120, kdy se jeden abstraktni zaznam nezkonvertuje spravne na jednorozmerne pole
- okno editoru pri mazani znaku tagu muze zamrznout

Reseni je ve vetvi `transposition_bugfix`. Nicmene to nepodporuje ten zapis 
```
bc_flux: !FieldFormula
  value:
    - x+y
    - y+z
```

Snazil jsem se najit nejake jednoduche reseni, ale bohuzel jsem zadne nenasel. S timhle jsem z principu vubec nepocital, protoze pouziti tagu automaticky znamena zaznam. Je potom problematicke, kdy se ma ukoncit prochazeni, jaka ma byt skutecna delka transpozice atd. Bylo by to kompletni predelani transformace. 

Transformaci jsem navrhl s ohledem na to, jak to funguje YAML.  Myslel jsem, ze se pro vyse uvedeny priklad bude pouzivat nasledujici zapis, ktery funguje:
```
bc_flux:
    - !FieldFormula x+y
    - !FieldFormula y+z
```

Pokud se to ale bude predelavat, tak bych tu traspozici potreboval kompletne naspecifikovat, idealne pomoci testu resp. kompletnich funkcnich prikladu, protoze po tech nekolika dalsich zmenach uz sam nevim, co ma vlastne fungovat a jak.

**Comment by jbrezmorf** [comment]
Pole uvnitř transpozice jsou nutná, například:

anisotropy: !FieldConstant
	- [ 1 2 3]
 	- [4 5 6]

... je potreba, protoze hodnoty Field mohou byt i vektory a tenzory.

**Comment by jbrezmorf** [comment]
Souhlasím s tím, že se transpozice musí lépe naspecifikovat a promyslet, možná i přepsat (do implementace nevidím)
Ve Flow je transpozice implemntovana nasledovne:
1. Načte se YAML pomocí nějaké knihovny
2. Vzniklá stromová struktura se prochází do hloubky a konvertuje na naší interní stromovou strukturu, behem toho se delá kontrola a vsechny automaticke konverze.
3. Speciálně pokud se podle IST očekává Array of Type ale v YAML je něco jiného provede se:
	1. čtení z YAML s kontrolou vůči Type, přičemž se zapne příznak, že jsem uvnitř transpozice (a pokud je někde v YAML pole a má tam podle IST být něco jiného, tak se to pokusi transponovat)
	2. Když se Type čte do našeho interního stromu, zapíšou se tam i tagy jako speciální klíče "TYPE".
	3. Když je Type přečtený, provede se transpozice již nad naším interním stromem, kde jsou tagy klíče a proto se transponují spolu s ostatními daty.

**Comment by tomaskrizek** [comment]
V te moji verzi je mozne mit i pole uvnitr transpozice, takze lze pouzit:
```
anisotropy:
  - [1, 2, 3]
  - [4, 5, 6]
```

Pouze pokud je potreba vybrat u abstraktniho zaznamu typ (ktery neni vychozi), tak je potreba ho uvadet u kazde polozky a ne hromadne, napr.:

```
anisotropy:
  - !FieldFormula [x+y, x-y, z]
  - !FieldFormula [x*x, y*y, z*z]
```
se prekonvertuje na dva zaznamy, kde jsou FieldFormula, ktera obsahuji pole o trech polozkach - tedy tak, jak to ma byt.

**Comment by jbrezmorf** [comment]
Problem je, ze to potrebujeme podporovat v tomto tvaru:
anisotropy: !FieldFormula
  -  [x+y, x-y, z]
  -  [x*x, y*y, z*z]


... protoze takto to vypadalo v predchozi verzi a nechteli jsme na to delat transformaci, protoze to bylo reseno prave zavedenim automaticke konverze = transpozice.
