### ISSUE TITLE
Model Editor

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#118]
přesunout parsování yamlu do common

**Comment by tomaskrizek** [comment]
Presunul jsem vse z `ModelEditor/data` do `common/model_data` krome transformaci. Ty zavisi jeste na `ModelEditor/helpers/subyaml` a nevedel jsem, jestli budou potreba i jinde, tak jsem je zatim nechal pouze v ModelEditoru. IST byly presunuty do `common/resources/ist`.

Testy jsem taky presunul a vsechny probehnou v poradku. Po kratce zkousce GUI to take vypada, ze vse funguje.

@richtertul @radeksrb Mam jeste vytvorit nejakou funkci, ktera by zajistovala kompletni nacteni nejakeho YAML konfiguraku v dane verzi flow123d? V tom modulu `model_data` jsou vsechny potrebne funkce, ale je potreba je zavolat ve spravnem poradi. My jsme tuto logiku meli jinde (meconfig), takze neni primo soucasti knihovny. Proces nacteni ale probiha takto:

1. Nactu text souboru IST z `common/resources/ist/*.json`.
2. Pomoci `get_root_input_type_from_json(text)` ziskam `root_input_type`, ktery se dale pouziva pro autokonverze a validaci.
3. Nactu text konfiguracniho souboru (`yaml_text`).
4. Ziskam koren stromu (`root`) konfiguracniho souboru pomoci `Loader.load(yaml_text)`.
5. Provedu autokonverze pomoci `autoconvert(root, root_input_type)`.
6. Provedu validaci pomoci `Validator.validate(root, root_input_type)`.

**Comment by richtertul** [comment]
Transformace by měli být jen v modelEditoru. 

Funkce (možná spíš třída s nějakým rozhranním) by byla dobrá, Jen se prosímtě podívej do transformací, kde něco takového taky dělám. Nevím jestli tam potřebuji úplně všechny akce, ale i transformace by mohli volat tuto funkcionalitu. (Možná i meconfig, pokud se to tam nepoužívá trochu šířeji, nechám to na tobě)
