### ISSUE TITLE
Wrong error and autocomplete

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/GeoMop#120]
Model Editor:
[flow_implicit.yaml.txt](https://github.com/GeoMop/GeoMop/files/318449/flow_implicit.yaml.txt)

- hlásí chybu na řádku 38, která tam není
- kompletace na řádku 74 nabízí *anchor3

**Comment by tomaskrizek** [comment]
Autocompletion nabizi kotvy globalne, to je spis feature nez bug. Pokud ji uzivatel chybne pouzije, je upozornen validacni chybou. Kontrola, kde se anchor definuje a kde se ma nabizet, by se tam musela kompletne dodelat.

Chyba je zpusobena upravou transpozice, viz #115.

**Comment by jbrezmorf** [comment]
Jo trochu jsem to tak chapal. Nechme to otevrene dokud se nevyresi #115.
