### ISSUE TITLE
JobScheduler - refaktorovat nastavení presetů a dopsat testy

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#123]
- presety by měli jako klíč používat své jméno, které by mělo být jedinečné
- kontrolovat jestli daný preset existuje
- v testingu udělat funkci, která načte preset,mjs a nanlyzis z testovacího adresáře. V presetu zatím budou scénáře:
    
    - exec-exec
    - ssh-exec-exec
    - ssh-exec-ssh-exec

- udělat základní unit testy načtení presetu

**Comment by tomaskrizek** [comment]
Hotovo. Pro scenare jsem a unit testy jsem pouzil data z instalace (`GeoMop/data`).
