### ISSUE TITLE
Analysis - problémy v testech

### ISSUE THREAD

**Issue by radeksrb** [GeoMop/GeoMop#126]
Ahoj Pavle,
funguje vše až na dva testy, které jsem dal do souborů test2.py a test3.py.
Radek

**Comment by richtertul** [comment]
Opravil jsem, asi jsou potřeba upravit kontrolní soubory v testech, na řádku 49 v test_workflow_actions.py . Jsem dal return, aby to zatím procházelo.

**Comment by radeksrb** [comment]
Upravil jsem je.
