### ISSUE TITLE
Analysis - Flow123d Akce input output

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#127]
V common v analyzis budou funkce které pro každý yaml (a na něm závislé meshe) udělají soubor "jmeno_yamlu".sprt (jako support), sklásající se z informací o regionech, parametrech, ... . Ten soubor se nakopíruje na remote a při spuštění analysis se použije pro akci Flow123dAction ke kontrole vstupů a vygenerování výstupů. Jsou pro to připraveny funkce

    def get_require_params(self):
    def __file_output(self):
    def __parametrise_file(self):

 v Flow123dAction. První vrátí množinu očekávaných parametrů, aby šlo zkontrolovat input, druhá DTT strukturu výstupu flowa pro návaznou akci a třetí přejmenovaný yaml, který se použije při běhu flowa. V tomto souboru budou doplněny parametry podle výsledku předchozí akce. Funkce je možné přejmenovat a možná budou potřeba nějaké parametry přidat. Nejsem si jistý zda funkce pro doplnění známých parametrů do yamlu není hotová od Tomáše.

Všechno by to mělo být připraveno tak, že část se použije na PC a část půjde nakopírovat na remote. Ta část pro remote bude ve zvláštním adresáři a nebude obsahovat parsrování yamlus IST. (pokud by nebylo možné oddělit parserování, pak to může jít na remote vše, ale mám strach že by se museli řešit i nějaké návazné knihovny)

**Comment by richtertul** [comment]
Tomáši prosímtě mělo by to zapadat do toho co je již hotové. Mohl by jsi to trochu popsat bud sem, nebo se dohodnem v pondělí a někdo z nás to vysvětlí Radkovi.

**Comment by tomaskrizek** [comment]
Aktualne jsou parametry zapsane na dvou mistech - `analysis.data` a `.project`, oboji v adresari s projektem. To se ovsem bude spojovat do jednoho souboru.

Funkci, ktera by vzala vstupni text a vyhledala v nem parametry, jsem nedelal. Moje implementace je hledala jako soucast validace, pokud se narazilo na skalarni hodnotu - takze ta prvni funkce implementovana neni. Nicmene ocekavane parametry, ktere se nalezly v souborech behem editace v ModelEditoru, se zapisuji do `.project`. Tato informace ovsem slouzila hlavne pro potreby automatickeho doplnovani parametru a z principu tam nemusi byt aktualni a spravny seznam parametru. Doporucoval bych asi pro vyhledani parametru udelat samostatnou funkci. Melo by podle me stacit vyhledat v textu parametry podle regularniho vyrazu (`model_data.format.RE_PARAM`).

Uplne nerozumim popisu druhe funkce, ale pokud ma vracet vyparsovany IST format (treba `2.0.0_rc.json`), tak to dela funkce `model_data.format.get_root_input_type_from_json(data)`. Akorat je nutne nejprve otevrit a nacist data ze souboru, funkci se predava text toho json souboru.

Treti funkce, ktera doplni do zadaneho souboru parametry, uz je hotova. Jedna se o `replace_params_in_file(src_path, dst_path, params)` v `common/flow_util/analysis.py`. Vstupem je cesta ke vstupnimu souboru, cesta v vystupnimu souboru a slovnik s parametry, ktery obsahuje dvojice nazev_parametru => hodnota. Funkce otevre vstupni soubor, provede nahrazeni pomoci regularnich vyrazu a vystup ulozi do ciloveho souboru.

**Comment by jbrezmorf** [comment]
Nemyslim, ze je ucelne tyto extrahovane informace nekam ukladat. Ta
extrakce bude rychla takze je mozno ji na remote opakovat
a ukladani bude jenom delat problem s konzistentnosti (napr. kdyz se YAML
zmeni externi editaci).

2016-06-23 12:15 GMT+02:00 Tomas Krizek <notifications@github.com>:

**Comment by richtertul** [comment]
- parametry yaml souborů jsou ted ukládány protože se předpokládalo, že budou sdíleny mezi soubory, asi je bude lepší načítat vždy při otevření nějakého souboru, ale to je otázka pro jinou fázi vývoje, ted by to mělo zůstat jak je.
- data bych chtěl přenášet na remoute extraovaná  proto, protože na parsrování Yamlů je potřeba IST a nějaké knihovny. Pokud to půjde jednoduše (a asi by stačili dvě serializační metody o 20 řádcích), vidím to jako nerychlejší řešení, pokud ne, bude se parsrovat na remotu a bude to složitější, protože se budou installovat nějaké knihovny, přenášet ist,... . Problémy z konzistencí zde nejsou, protože se to dělá z nakopírovaných yamlů. Naopak je otázkou zda by se v opačném případě nemusela řešit konzistence IST.
