### ISSUE TITLE
Určení konfliktních bloků (pokračování #10)

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#13]
Rozmyslet další postup a zvolit řešení 
Připadá v úvahu:
1. Nedělat
2. Zkusit odstranit jen celé konfliktních bloky
3. Určení konfliktních bloků v případě že změnový blok zasahuje do struktury dokumentu nadřazeného nodu. Asi by nějak šlo z naposledy dobrého dokumentu určit hranice chybného bloku, případně parenta, nebo parenta parenta. Pomocí diffu pak přiřadit staré pozici nadřazeného bloku tu novou. A podle nové pozice pak určit změnový blok, jež je nutné zakomentovat.
Je nutné umět:
-najít nadřazený node ve starém dokumentu (naposledy dobrém dokumentu)
-přiřadit pomocí diffu staré pozici nodu tu v novém dokumentu
4. Zkusit vytipovat pár scénářů jak řešit je odděleně

**Comment by sha512rp** [comment]
Soucasny system mi pripada hrozne matouci a stejne tak reseni 2 nebo 3. Vynechavat cast kodu pri parsovani je takove hrozne nepruhledne, neni podle me pak prilis jasne, co se kdy vlastne deje (z pohledu uzivatele).

Myslim si, ze lepsi reseni by bylo vyzkouset, kdy v editoru muze nejcasteji dochazet k parsovacim chybam a pak jim predchazet. Pokud k ni ale stejne dojde, tak proste uzivatele donutit co nejdriv chybu opravit. Dokud ji neopravi, tak bych cely dokument bral jako nevalidni a prepnul bych editor do chyboveho rezimu - zmrazil strom a neumoznil zmenu hodnot, prepnul pozadi editoru nebo alespon chyboveho radku na cervene.

Odstranovani bloku muze zpusobit akorat vice chyb a je to neprehledne. Myslim si, ze je mozne dojit do stavu, kdy k parsovacim chybam bude dochazet pri psani jen vyjimecne pomoci dobre predikce na urovni textu a syntaxe. Pokud k ni dojde, tak je podle me nejlepsi dokument dal neparsovat a prioritou by mela byt oprava chyby ze strany uzivatele.

**Comment by richtertul** [comment]
- nějak si nedokážu představit co myslíš tím předcházením
- pokud se do dokumentu něco nakopíruje, smaže větší část, ... , musíme se k tomu nějak postavit
- za mě bych zkusil vlevo v editoru označit červeně rozsah erroru a pokud bude chyba závažnější, tak jej protáhnout do konce dokumentu (už jsem to popisoval v mailu)
- něco podobného 3) zkouším v tranformaci a zdá se že to funguje
-ted bych to odložil, myslel jsem že to máš rozdělaný a chceš to někam dotáhnout, pokud ne doděláme označení rozsahu chyb a zbytek odložíme až budu mít více času prozkoumat jak se chová současný editor.

**Comment by richtertul** [comment]
Bude se řešit později
