### ISSUE TITLE
Analysis - Hashes

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#130]
Dotažení práce s hashema. V akcích se ted vytvářejí hashe a je tam funkce get_hash kterou možná zrušíme. Vytvořit novou funkci get_hashes_list, která bude procházet vnořené akce a vytvoří seznam store_id->hash. Tento seznam bude možné uložit do souboru, nebo porovnat se starým seznamem. Z porovnání vznikne identical_list což bude seznam id se stejnými hashema, tedy seznam store_id->restore_id(old store id). Ten je možné po deserializaci předat pipeline processoru do konstruktoru. (Je připravené) Z processoru se bude volat funkce _set_restore_id pipeline, která proleze všechny akce a nastaví restore id (podle shody se store id)
 
- [x] přidání funkce _get_hashes_list do všech akcí (pipeline)
- [x] funkce _get_hashes_list - testy
- [x] testy pro hashe obecně - ověření že reagují na změny imputů, souborů, předchozích akcí (do nějakých vhodných akcí)
- [x] třída pro funkce, serializaci a deserializaci  compare_listu (client_pipeline)
- [x] compare_list - testy
- [x] třída pro funkce, serializaci a deserializaci  identical_listu (pipeline)
- [x] identical_listu - testy
- [x] třída pro vytvoření  identical_listu a compare_listu (client_pipeline::identical_list_creator)
- [x] vytvoření  identical_listu a  compare_listu - testy
- [x] přidání funkce _set_restore_id s parametrem identical_list do všech akcí (pipeline)
- [x] funkce _set_restore_id  - testy
- [x] doplnit do finkce PipelineProcessoru  _establish_processing volání _set_restore_id a otestovat
- [x] otestovat v rámci pipeline processoru funkčnost hashů
- [x] zkontrolovat a napsat testy na to že PipelineProcessor při běhu načítá výsledky ze souborů (restore_id) a ukládá výsledky do store_id 
- [ ] zdokumentovat tuto funkcionalitu na vhodné místi asi client_pipeline::identical_list_creator

**Comment by jbrezmorf** [comment]
Je nejaky duvod ukladat hashe mimo akce, tj. v separatnim listu? Prijde mi,
ze je lepsi, kdyz to je zapouzdrene v akci, pak je mozne to spolu s akci
nekam presunovat a pod.


2016-06-24 7:22 GMT+02:00 Pavel Richter <notifications@github.com>:

**Comment by richtertul** [comment]
Moc nerozumím, akci máš předepsanou v python souboru bez hashů. Hashe se udělají až po inicializaci a to ještě někdy v závislosti na externích souborech. 
Je jen otázka zda je vůbec ukládat. Podle mě uložit je před spuštěním ze zmražených podkladů (Zde je otázka co s mashema, které chceš odkazovat, kterou budem řešit dnes) je docala výhodné.
  - bude kontrola nad tím, jestli se soubory nezměnily
  - udělat dvě pipeliny v paměti a ty pak porovnávat sebou nese určité komplikace díky execu. 
Možná myslíš ukládat do dat akcí, které se vytvářejí na remotu, ty by se pak museli procházet, a to by bylo docela komplikované a zbytečné. Navíc tento soubor ani na remote nemusí přijít.
