### ISSUE TITLE
Unable to parse document

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/GeoMop#134]
Novy dokument s obsahem:
flow123d_version: "2.0.0_rc"
  problem: !
Za vykricnikem:
- nefunguje doplneni
- pro prvni radek hlasi nesmyslne varovani:
  750 (Flow123dVersionMismatch): Using Flow123d version 2.0.0_rc instead of 2.0.0_rc problem.
- pro druhy radek hlasi: 
  101 (SyntaxFatalError): Unable to parse remaining input
  podle stromu vlevo parser nacte i 'problem:' jako obsah klice 'flow123d_version'

**Comment by richtertul** [comment]
Po úpravách to nehlásí nesmyslnou chybu, ale asi duplicitně:
309 (MissingAbstractType): Missing record type
457 (UnsupportedExpansion): Expansion abstract parameter to reducible key error
prosím otestovat a rozhodnout zda to tak může zůstat

**Comment by richtertul** [comment]
Chybi ok, zkontrolovat aut. dopln.
