### ISSUE TITLE
Null value for array or record

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/GeoMop#135]
Soucasne chovani:
1. Pri pritomnosti tagu se klic automaticky chape jako Abstract
   Priklad:
   
   ```
   format: !gmsh # Abstract, empty Record
   other_key: ...
   ```
2. Hodnota null se chape jako skalar (a je zahrnuta do autokonverzi)
   
   ```
   some_record: # try to apply auto conversion, fails trying set scalar to null
   some_array: # = [ null ], fails
   other_key: ...
   ```

Pozadovane chovani:
Hodnota null se v pripade klice typu Abstract, Record, Array chape jako {} resp. [], tj. prazny record ci prazdne pole. Konverze nenastanou protoze vstupni typ odpovidat pozadovanemu.

**Comment by richtertul** [comment]
Asi to budu potřebovat trochu objasnit. Například ted řešíme.
problem:
`
s Pavlem jsme narazili na problém při validaci testovacích .yaml souborů z flowa (např. toho co je v příloze). Objeví se chyba:

302 (ValidationTypeError): Expected type Record

na 7. řádku

flow123d_version: 2.0.0
problem: !Coupling_Sequential
  description: Test1 - Steady flow with multidimensional connections 1D-2D-3D
  mesh:
    mesh_file: ./input/test1_new.msh
  flow_equation: !Flow_Darcy_MH
    output_specific:       <--------------------------
    nonlinear_solver:
      linear_solver: !Petsc
        r_tol: 1.0e-10
        a_tol: 1.0e-10 
`
odpoved:
`
Flow123d v tomto případě interpretuje hodnotu output_specific jako NULL, takže jeko kdyby tak ten klíč nebyl. Takže je to chyba ve validaci, maximálně by to mohlo vyhazovat nějaký warning, že se klíč ignoruje.
`
Zde jako by to nebyl prázdný record, ale naopak NULL?

**Comment by richtertul** [comment]
Snad hotove
