### ISSUE TITLE
Transposition tests

### ISSUE THREAD

**Issue by tomaskrizek** [GeoMop/GeoMop#136]
Vytvoril jem testovaci soubory pro transpozici v `testing/common/model_data/autoconversion`. Je potreba zkontrolovat spravnost predpokladanych vystupu pro nasledujici testovaci soubory:

- [ ] 2.0.0_rc-transpose_duplicate_two_dim_array.yaml
- [ ] 2.0.0_rc-transpose_duplicate_array_same_length.yaml
- [ ] 2.0.0_rc-transpose_duplicate_two_dim_array2.yaml
- [ ] 2.0.0_rc-transpose_abstract_with_tag_two_dim.yaml
- [ ] 2.0.0_rc-transpose_complex.yaml
- [ ] 1.8.3-transpose_duplicate_two_dim_array.yaml
- [ ] 1.8.3-transpose_duplicate_two_dim_array2.yaml

Dale si nejsem jisty, jestli by transpozice mela umet nasledujici:
- [ ] 2.0.0_rc-transpose_abstract_with_different_tags.yaml

Pokud nektere bezne (nebo specialni) pripady pouziti nejsou v techto testech zachyceny, bylo by dobre je dospecifikovat.

**Comment by richtertul** [comment]
Tak snad je to hotový
