### ISSUE TITLE
autokonverze

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#14]
implementovat auktokonverze v datove strukture

1. zmena na `Record`
  pokud:
  1. se na vstupu podle formatu ocekava `Record` a misto nej je `Scalar` nebo `Array` a zaroven
  2. ocekavany `Record` ma uveden `reducible_to_key`

  pak vytvorit `CompositeNode` pro `Record` a na jako klic urceny pomoci `reducible_to_key` doplnit puvodni `DataNode`

2. zmena na `Array`
pokud se na vstupu ocekava `Array` a misto nej je `Scalar` nebo `Record`, pak vytvorit `CompositeNode` pro ocekavany `Array` (pripadne vic do sebe vlozenych - podle ocekavane dimenze pole) a jako jeho jediny prvek vlozit puvodni `DataNode`

**Comment by sha512rp** [comment]
Jeste potreba tuhle feature poradne otestovat. Nejsem si jisty, zda korektne funguje pro vsechny mozne kombinace `AbstractRecord` + reference + autokonverze.
