### ISSUE TITLE
Generovani html pro info_panel

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#15]
-prozkoumat stávající knihovnu

**Comment by sha512rp** [comment]
Pujde prevzit cast kodu pro generovni html z json. V kodu bude ptreba udelat mensi zmeny (napr. negenerovat linky, generovat pouze jeden zaznam atd.)

QTextEdit by mel podporovat css pres QTextDocument.setStyleSheet(), takze vysledek by mel vypadat podobne.

**Comment by richtertul** [comment]
OK, bude se řešit v dalším issues
