### ISSUE TITLE
Me - zpracování a vyřešení nahlášených bugu

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#152]
[problémy](https://docs.google.com/document/d/1dfszIgCss62rXgTf_R-lWh-a5jhmqWkle73VxfLACpM/edit?usp=sharing)

- vyřešit jednoduché úkoly
- vytvořit nové issues pro zbytek

**Comment by jbrezmorf** [comment]
Rozbit do jednotilvych issue.
