### ISSUE TITLE
Me - Pomalé načítání souborů

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#154]
Přiložený soubor s odkazy se pomalu načítá.

[flow.yaml.zip](https://github.com/GeoMop/GeoMop/files/905363/flow.yaml.zip)

**Comment by richtertul** [comment]
Částečně vyřešeno. Ještě zkusit profilovat a počkat na potvrzení.

**Comment by jbrezmorf** [comment]
TODO: Nutno otestovat.

**Comment by jbrezmorf** [comment]
Otestovano, funkguje pouzitelne.
