### ISSUE TITLE
me - chytré odsazování

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#155]
Nevěděl jsem co má být za balance, původní pokus "balance: {true}" reportuje chybu.
Napíšu teda jen "balance:" ale v modrém poli vidím jen obecný popis co to je a default hodnotu {}. Problém je že nevím, kdy za dvojtečku píšu přímo a kdy na další řádek s odrážkou.

A. Jde o vlastnost yamlu:
    a: {b: bb,c: cc}
    ==
    a:
        b: bb
        c: cc

    a: [b,c]
    ==
    a:
        b
        c
Podle mě jeho intuitivnímu pochopení brání míchání flow stylu a obyčejného yamlu zápisu. Navíc nápověda používá první a editor doporučuje druhý.

V připravované nápovědě popsat tento rozdíl?
Udělat yaml tutoriál, nebo jen odkázat něco jednoduchého?
JB:  V manuálu Flow je YAML popsán včetně flow stylu. Asi by bylo vhodné toto použít a případně doplnit pro dokumentaci ModelEditoru.
Částečně související (viz. dále):
v napovědě zdůraznit nějak typy: Array, Record, Tuple
(chytré odsazování) po odřádkování odsadit nebo odsadit s pomlčkou podle toho jestli je tam Record/Tuple nebo Array? Každopádně by se tak člověk ocitl ve správné nápovědě.

**Comment by jbrezmorf** [comment]
Castecne vyreseno.
