### ISSUE TITLE
me - nápověda za klíčem

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#156]
Takže když nyní dám crtl-space a nabídne mi volby a nějakou vyberu, umístí ji na stejný řádek a to generuje další chybu a zároveň místo kontextu se v modrém poli objeví "root". Teprve když správně odřádkuju a odtabeluju, objeví se v modrém poli relevantní informace podpoložek z balance co je co.

B. Problém je že editor v našeptávání ukazuje i volby, jež je možné napsat jen na další řádek, nebo uzavřít flow stylem. Našeptávání je hloupé a nekontroluje co je před kurzorem na řádku. Řešením by byla tato kontrola a bud vyřazení věcí co nejsou v daném kontextu korektní z našeptávání, nebo následné odsazení.  
To že při nevalidní syntaxi spadne nápověda do rootu je vlastnost. Přesná lokalizace pozice kurzoru v IST by vyžadovala  velmi složitou logiku. V budoucnu bych chtěl podle určitých pravidel vytvářet paralelně kopii dokumentu  bez nevalidních části yamlu a výsledek použít pro lepší našeptávání a popis chyb v messages, případně dalších věcí. To je však rozsáhlá věc.

Filtrovat, odsazovat, nebo prohlásit za vlastnost?
Našeptávat podle ist i „[“ , „{“ ?
JB: Asi by mohlo být vhodné napovídat za dvojtečkou již pro daný klíč. Mám pocit, že jsme něco takového už řešili. 
Skákání na nápovědy ROOT je skutečně nepříjemné, bylo by možné tam jen nechat poslední nápovědu? 

U bc_type to v modrém poli nenabízí jaké typy můžu zadat ale jen obecně field R3 to R v zeleném poli. I ctrl-space v editoru nabízí jen value nebo !FieldXXX. Chtěl bych nabídku dirichlet/total_flux/atd.

**Comment by jbrezmorf** [comment]
Opraveno. 
bc_type: rozsireni naseptavace nebo TreeView
