### ISSUE TITLE
me - přehodit broeser v IST nápovědě + dořešit následující

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#158]
Vybraný text z modrého pole nejde kopírovat do schránky (chtěl jsem se na něco odkázat v dotazu), naopak ctrl+c se v tu chvíli chová tak, že obsah modrého pole vrátí do kontextu kurzoru v editoru (poté co jsem předtím přebrouzdal jinam) - možná je to záměr, ale toto není jako kláv zkratka specifikováno.

 To co je v tabu dole, je nějaký widget s html editorem, kterému podstrčíme html soubory. Nemáme ho plně pod kontrolou a hacknutí zkratek nikdo nezkoušel. Navíc je v nové verzi QT nahrazen jiným prvkem (webkit, jinou implementací browseru) a případné opravy by to chtělo dělat tam. Asi bych to odložil minimálně do doby, než bude nové qt součástí distribucí. Pak by bylo také potřeba updatovat windows verzi.

Vyměnit widget (priorita)? 
JB:  Řešit v rámci změny widgetu, časem, nebo pokud jeho změna bude nevyhnutelná (konec podpory ..).

Nerozumím popisu klíče step u TimeGrid - text píše, že při nespecifikované hodnotě dělá výstup jen v start time, což mi přijde nelogické.

**Comment by jbrezmorf** [comment]
Webkit vymenen.
TODO:
Podpora Ctrl-C v okne napovedy. Pro instanci QtWegEngineView je treba predefinovat funkci prislusne zkratky (Ctrl+C), nicmene Ctrl+Insert funguje.
