### ISSUE TITLE
Vytvoreni package pro pip

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#16]
- najít postup jak udělat balíček
- navrhnout adresářovou strukturu pro build (najít jak se to obvikle dělá)
- vytvořit postup do src dokumentace
- vytvořit instalační postup do dokumentace

**Comment by sha512rp** [comment]
Postup instalace pridan do dokumentace. Obsahuje

- instalaci pozadavku,
- pouziti virtual envirotnment,
- spusteni github kodu.

Napsal jsem to anglicky a snazil jsem se to napsat univerzalne pro obe dokumentace. V uzivatelske dokumentaci se akorat vynecha instalace pozadavku a spousteni z githubu.

Issue povazuji za uzavreny, protoze nakonec nebudeme pouzivat pip package, ale debian package.
