### ISSUE TITLE
Model Editor - fatal err

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#17]
Místo info udělat fatal errory
  - fatal error může být jen jeden
  - fatal error bude od sporné pozice do konce souboru
  - tree se bude zobrazovat jen pro strukturu před ním
  - errory budou seřazeny podle začátku výskytu

**Comment by sha512rp** [comment]
Vyreseno. 65968ea6780b15424a1b92d09c5d32ff978ab71c

V nekterych pripadech se nepodari vyparsovat strukturu ani pri zakomentovani fatal erroru, potom se do tree nastavi None
