### ISSUE TITLE
Model Editor - stabilizace

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#18]
Otestovat stávající aplikaci a odstranit problémy.
Zjištěné problémy:
  - (opraveno --TK) status bar a černé panely
  - (opraveno --TK) error.span == None

**Comment by richtertul** [comment]
- Config_valid.yaml -> před "balance: true" dát "{ " a za ","

The debugged program raised the exception unhandled UnboundLocalError
"local variable 'node' referenced before assignment"
File: /home/pavel/work/GeoMop/src/ModelEditor/data/yaml/loader.py, Line: 109

**Comment by sha512rp** [comment]
Vsechny Exceptions, ktere se vyskytly behem testovani, jsem opravil. Issue nechavam otevreny pro zaznamenavani dalsich vyjimek, ale prozatim ho povazuji za uzavreny.

Dalsi chyby, ktere se pri testovani vyskytly jsem zaznamenal do https://docs.google.com/spreadsheets/d/1czNMJsB8bu3kaa-gKFNQdUbUXgquoDzIscbWaarZ5sA/edit?usp=sharing

**Comment by richtertul** [comment]
Uzavírám, na další chyby se otevře nový task.
