### ISSUE TITLE
Model Editor - přehled errorů pro analýzu

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#19]
Přípravit dva excely s přehledm chyb (název, popis, jak naszmulovat, závažnost)
  - chyby vedoucí k fatal erroru
  - zvláštní chování o kterém by jsme mohli chtít informovat uživatel

**Comment by sha512rp** [comment]
Spreadsheet s chybami dostupny z: https://docs.google.com/spreadsheets/d/1czNMJsB8bu3kaa-gKFNQdUbUXgquoDzIscbWaarZ5sA/edit?usp=sharing

Obsahuje dva listy - jeden pro obecne chyby, druhy pro fatal errory
