### ISSUE TITLE
ModelEditor - Info

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#20]
1. Prozkoumat QTextEdit  a jeho podporu StyleSheetu a java scriptu ( QtWebKit, podívat se i na závislosti a jejich podporu pod windows )
2. Vygenerovat html z načteného Jsonu pomocí knihovny Flow123d-python-utils (Honza Hybš)
3. Svázání format typů s ID elementy v html souboru 
4. Zkusit něco zobrazit (visuální podoba se bude řešit v další fázi)

**Comment by sha512rp** [comment]
add 1.
Doporucuju pouzit QTextEdit. Ma omezenou podporu HTML a CSS, ale nejake zakladni formatovani s tim urcite udelame. Javscript nepodporuje, takze zobrazeni rovnic budeme muset resit asi pres obrazky.

QtWebKit by pod linuxem nebyl problem, ale pod Windows by kazda instalace byla dost komplikovana. Muselo by se to [sestavit ze zdrojaku](https://trac.webkit.org/wiki/BuildingQtOnWindows) a ma to spoustu zavislosti.

**Comment by sha512rp** [comment]
Update pro 2ea7cda18869698de7e51425a483df104ddc96c3:
Info panel zobrazi prislusnou cast HTML dokumentace vcetne formatovani.
Aktualne nejde a je potreba dodelat:
  - js odkazy
  - js rovnice
  - upravit generovani html pro podporu odkazu (pomoci data-id)

Dale by to chtelo vyresit, jak importovat knihovnu. Problemy jsou dva - jednak je knihovna v Pythonu 2 a zaroven bych potreboval udelat nejake zmeny primo v knihovne, aby to generovalo dokumentaci pro potreby ModelEditoru trochu jinak. Prozatim jsem knihovnu prevedl do Pythonu 3, prekopiroval uzitecnou cast a upravil podle potreby.

Take je potreba vyresit, kam umistit resources (css, js) a nastavit jim odpovidajici url.

**Comment by richtertul** [comment]
OK
