### ISSUE TITLE
Model Editor - reference

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#21]
Implementace yaml referencí:
  1 - klasické reference & ( anchor ) - * ( reference )
  2 - merge  & ( anchor ) - <<:* (merge )
Reference budou načteny a zkontrolovány, do tree se zkopírují itemy z odkazovaného node a budou ukazovat na něj

**Comment by sha512rp** [comment]
anchor/alias pridano v ada6b34ce30b2d97baf1d97eabc636cf13628793
potreba opravit: aktualne se zkopiruje i type
