### ISSUE TITLE
JP - Selections in multjob list

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/GeoMop#219]
- [x] Context menu, kopie od Multijob hlavniho menu.
- [x] Moznost vyberu radek (klik, Shift klik, Ctrl klik), Shift kurzor - vyber, viz. vyber souboru v PyCharm
- [x] Pro vybrane budou povoleny pouze operace 'Delete remote', 'Dlelete MJ', 'Stop*. 
       Vyvola se potvrzovaci 	 dialog se seznamem MJ pro ktere je operace povolena.
	Pro vyber velikosti jdna, soucasne chovani.
- [x] Pri refresh tabulky, obnovit vyber. 
- [x] Pro novy MJ nastavit vyber na nej.
- [x] main_menu_actions.py - delat instance QAction primo (pomoci funkce).

**Comment by TomasBlazek1** [comment]
Momentálně je potvrzovací dialog vyvolán i v případě, že je vybrán jen jeden MJ. Myslím si, že by to takto mohlo zůstat, jelikož se jedná o potvrzení mazání a zastavování akce.
