### ISSUE TITLE
LE - file loading fails on surface loading

### ISSUE THREAD

**Issue by MMatusu** [GeoMop/GeoMop#223]
* Bug reproduction: load any file
* End of error statement:
  *  File "le_serializer.py", line 195, in geometry_to_cfg
    cfg.reload_surfaces(gf.geometry.supplement.surface_idx)
  *  File “leconfig.py", line 203, in reload_surfaces
    cls.main_window.wg_surface_panel.change_surface(id)
  *  File "panels\surfaces.py", line 492, in change_surface
    self.data = SurfFormData.init_from_surface(self.layers.surfaces[new_idx], new_idx)
  * IndexError: list index out of range

**Comment by jbrezmorf** [comment]
Can not reproduce with any file. Attach JSON to reproduce the bug.

**Comment by jbrezmorf** [comment]
Reproduced, fixed in master.
