### ISSUE TITLE
LE - coloring issue with 1D elements

### ISSUE THREAD

**Issue by MMatusu** [GeoMop/GeoMop#224]
* Bug reproduction:
  * assign 1D region in layer (that is to a point in projection)
  * switch displayed in layer panel to a fracture.
  * Point (now 0D - just a point in fracture layer) is still colored by the 1D region discussed previously.
  * Region color is updated right upon selection of the problematic point.
* Just a coloring issue in ui, data layer is correct as it updates well when selected.

**Comment by jbrezmorf** [comment]
Can not reproduce.
