### ISSUE TITLE
LE - Meshing does not work

### ISSUE THREAD

**Issue by MMatusu** [GeoMop/GeoMop#226]
* Bug reproduction:
  * Simple polygon, no surface, assign proper dimension region, set mesh_step (e.g. 3 for init area, polygon about 20x20)
  * Save, try to mesh - > 'Process failed to start’ error message popup
* Message je tvoreny v dialogs->make_mesh->MakeMshDlg._proc_error() co je nalinkovany na jakykoli problem se startem processu meshovani.
* Jak zjistit co zpusobilo problem?

**Comment by jbrezmorf** [comment]
Asi to bude tim, ze nemas GMSH. Ale melo by se to lepe osetrit. Provedu.

**Comment by jbrezmorf** [comment]
final solution in #247
