### ISSUE TITLE
LE - elements movement operations are not connected as well as normal creation

### ISSUE THREAD

**Issue by MMatusu** [GeoMop/GeoMop#229]
* tested in master
* Bug reproduction:
  * Shape - polygon s jednou line dovnitr 
  * Pri vytvoreni deleni polygonu na dva pomoci tazeni vnitrni line(koncoveho bodu) na polygon boundary line
  * File GeoMop\src\LayerEditor\ui\data\polygon_operation.py", line 177, in _reload_boundary
    lines, qtpolygon = self._get_lines_and_qtpoly(diagram, polygon)
  * File GeoMop\src\LayerEditor\ui\data\polygon_operation.py", line 265, in _get_lines_and_qtpoly
    raise Exception("Can't find polygon line in diagram")

**Comment by jbrezmorf** [comment]
Just check for collision during move do not allow joining with existing lines and points.
