### ISSUE TITLE
GeoMop - update vývojářské dokumentace po push

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#23]
Dokumentace je v branch gh-pages. Na http://geomop.github.io/GeoMop/ se zobrazí co je tam nakopírováno. Chtělo by vymyslet způsob jak automaticky po push generovat dokumentaci a kopírovat ji tam.

**Comment by sha512rp** [comment]
Vyreseno pres pre-push hook, viz e-mail.
