### ISSUE TITLE
LE - when moving elements changes in ui do not propagate to data layer

### ISSUE THREAD

**Issue by MMatusu** [GeoMop/GeoMop#230]
* ‘Ghost geometry’ Zmeny v Diagram se nepropaguji do data layer pri tazeni elementy.
* Bug reproduction:
  * polygon s jednou line dovnitr
  * pri hybani jejim koncovym bodem se vse chova (envelope obstruction) jako kdyz je puvodni pozice line stale na miste.
* Castecne dela problem, ze clovek nevidi puvodni bod elementy, t.j. Neni jasny displacement vektor.
- [x] Solve geometry propagation
- [x] Original points faint brush should be still left behind, so the behaviour makes sense.

**Comment by MMatusu** [comment]
Problem se zda byt v numerice. Vyhodnoceni seg_intersection dvou sousedicich segmentu je pravdepodobne na vine.
gm_base -> polygons -> polygons - PolygonDecomposition.check_displacement() a v nem pak seg_intersection. Hodnoty parametru metody se zdaji byt ok, nachazi prusecik i mimo 'ghost boundaries'..

**Comment by MMatusu** [comment]
20.11.2018 TODO:
 - [ ] Otestovat a vyresit numerickou issue
 - [ ] TODOs v check_displacement, predevsim itnersekce s ostatnima wire (zatim reseny jen pro boundary v ramci polygonu, zvenci dovnitr je mozne tahnout cokoli)

**Comment by jbrezmorf** [comment]
resolved #251
