### ISSUE TITLE
LE - missing update of region panel after change in Layers panel

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/GeoMop#240]
Reproducing steps:
- create new layer in layers panel
- just single tab remains in the regions panel until some region operation is done in the diagram

**Comment by MMatusu** [comment]
Seems fine in current master after several tests, perhaps to be discussed at a meeting.
Perhaps it is not shown because it's in a different layer block, which is intended behavior...

**Comment by jbrezmorf** [comment]
seems resolved.
