### ISSUE TITLE
JobsScheduler - Add new MultiJob (dialog)

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#26]
Dialog který  umožní přidání MultiJobu.
Bude obsahovat:
Name - jméno, které půjde použít při vytvoření souboru (kontrola)
Analisys - adresář se strukturou úlohy
Description: Text jen pro čtení, který se načte z adresáře v Analisys (Zatím si tam dej nejaký soubor)
Resource - načteno ze settings::resource
LogLevel - hodnoty z python modulu logging
Number of Proc.

Serializace přes lib/config, do adresáře mjs/name.yaml (podívat se do ModelEditoru meconfig.py - class _Config)

**Comment by johnymachine** [comment]
Předběžný návrh Add new MultiJob Dialog
![image](https://cloud.githubusercontent.com/assets/2737699/9516713/c8391470-4caa-11e5-9cb4-6efbe59f9a45.png)

**Comment by jbrezmorf** [comment]
Seems good for the first try.

JB

On 08/27/2015 11:00 AM, Jan Gabriel wrote:
> Předběžný návrh Add new MultiJob Dialog
> image
> <https://cloud.githubusercontent.com/assets/2737699/9516713/c8391470-4caa-11e5-9cb4-6efbe59f9a45.png>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoMop/GeoMop/issues/26#issuecomment-135349780>.
> 

-- 
------------------------
Mgr. Jan Brezina, Ph. D.
Technical University in Liberec, New technologies institute
http://www.nti.tul.cz/cz/WikiUser:Jan.Brezina

**Comment by johnymachine** [comment]
![snimek obrazovky porizeny 2015-08-30 13 00 55](https://cloud.githubusercontent.com/assets/2737699/9566874/5558af96-4f17-11e5-92f5-a4d073e7c93a.png)

Překlopeno do kódu, a vytvořena šablona pro podobné dialogy.
ToDo:
 - [ ] Zadrátování funkčnosti
 - [ ] Serializace dat
