### ISSUE TITLE
JobsScheduler - SSH presets (dialog)

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#27]
Seznam SSL presetu, do kterého jde přidávat, editovat a mazat.
Sloupce:
name, host (ip,domena), uid, password (sloupce se budou možná měnit)
-zvážit zda nejde udělat šablonu pro presety (#30)
Serializace přes lib/config, do adresáře mj_ssl/name.yaml

**Comment by johnymachine** [comment]
# Předběžný návrh SSH Presets (dialog)

(Seznam SSL presetu, do kterého jde přidávat, editovat a mazat.)
**Sloupce** - Id, Name, Host, User, Password
**Implementovat guard proti smazání používaného.**

![image](https://cloud.githubusercontent.com/assets/2737699/9519746/a51c180e-4cc1-11e5-8e80-636710c26400.png)

**Klávesové zkratky:** CTRL + První písmeno tlačítka
*Editace vyřešena jako inPlace se společným Save a Discard pro všechny.*

Serializace přes lib/config, do adresáře mj_ssl/name.yaml

**Comment by richtertul** [comment]
1. Představoval jsem si že místo posledních 4 sloupců bude jeden, v němž bude pro každý preset   nějaký obecný popis, protože:
  a. Počet parametrů s implementací poroste
  b. Pro #28 a #29 je počet parametrů velký, nebo si nedovedu představit jejich sloupcovou reprezentaci
  c. Půjde udělat společná třída pro všechny tyto dialogy
2. Nevím kde dialog bude umístěn (představoval jsem si spíš header s comboboxem v záhlaví volby SSH, pbs, ...). Pak by asi nebyl potřeba popis, ten by se zobrazil při volbě name 
  a. Pokud to bude mezistupen pro volbu presetu, pak tam nebude Discard Changes a Save All, ale jen edit a delete. Save bude při zavření dialogu s jednotlivým presetem.
  b. Pokud je to header. pak bys asi musel nějak zvýraznit změněné hodnoty, ale radši bych nechal hodnoty uložit po změně výběru presetu

Ještě si o tom promluvíme zítra.

**Comment by jbrezmorf** [comment]
Myslím, že stačí se omezit na sloupce: name, host, user
ID je implementační detail, který nemá smysl aby uživatel viděl; heslo bude třeba nahrazeno certifikátem a jak zmiňuje Pavel pár parametrů může přibýt, např. pracovní adresář GeoMopu pro dané připojení.
