### ISSUE TITLE
node_graph - test 2.7.

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/GeoMop#278]
- [x]  can not create new workflow in current module
- [x]  can not create new module
- [x] can not open particular workflow of the module, context menu in the panel "Module" doesn't work
- [x] save last directory in Open dialog
- [x] delete of a connection also removes other connections
- [x] unable to detach end of a connection and connect to other slot (should work with Alt-click)
- [x] unable to pan the scene (just zoom), Ctrl+left=select, Left=pan

**Comment by TomasBlazek1** [comment]
- delete of a connection also removes other connections: When connection to result action is deleted, action Value_1 of type Value is created and connected to result.

**Comment by TomasBlazek1** [comment]
Idea: connection should detach if user clicks on input port of that connection. If (ctrl) is pressed connection stays connected to input port, but output port is detatched.

**Comment by TomasBlazek1** [comment]
Idea: change graph orientation to horizontal

**Comment by TomasBlazek1** [comment]
Idea: merge Toolbox and Module panel to avoid duplicit information

**Comment by TomasBlazek1** [comment]
Issue bych udělal až v novém repozitáři.

**Comment by TomasBlazek1** [comment]
All issues resolved in branch https://github.com/GeoMop/GeoMop/tree/TB_new_analysis_modifications.
Some ideas left to be considered later.
