### ISSUE TITLE
JobsScheduler - PBS Presets (dialog)

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#28]
Seznam PBS presetu, do kterého jde přidávat, editovat a mazat.
Sloupce:
name,??? (sloupce se budou možná měnit)
-zvážit zda nejde udělat šablonu pro presety (#30)
Serializace přes lib/config, do adresáře mj_pbss/name.yaml

**Comment by johnymachine** [comment]
Kofigurace uzlu

**Comment by johnymachine** [comment]
be96d17a107f1b32fbcf4d52b7eeb54bc8ad4571
