### ISSUE TITLE
JobsScheduler - Resource presets (dialog)

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#29]
Seznam resource presetu, do kterého jde přidávat, editovat a mazat.
Sloupce:
name, popis struktury bude upřesněn
-zvážit zda nejde udělat šablonu pro presety (#30)
Serializace přes lib/config, do adresáře mj_resources/name.yaml

**Comment by johnymachine** [comment]
Nabízí se opět stejné řešení jako #27 a #28 potřebuji vědět hlavičky a jejich složitost.
