### ISSUE TITLE
Improvement of data layer in Layer Editor

### ISSUE THREAD

**Issue by TomasBlazek1** [GeoMop/GeoMop#299]
Right now the code is segmented into many classes, where sometimes the code is exactly the same or the class contains only few methods. Therefore when Layer Editor will be nearly finished, some objects could be reduced or replaced by one object containing all common function.
This is mostly true about `...Model` objects which acts as a collection of `...Item` objects. `...Model` has methods for loading/saving to format_last.py and adding/removing `...Item` objects.
Some `...Item` objects may be replaced with corresponding objects from format_last.py. (Unlikely)

Another issue may be loading data from format_last.py which is currently done in constructor. The proposition is to make a static/class method which would create the object which would leave the constructor for creating additional data.

This is a finishing task and therefore it should be done when Layer Editor is nearly done including debuging/testing.

**Comment by jbrezmorf** [comment]
We should start to use a common collection class as soon as possible. The point is that it would be problematic to separate common and specific code after things get complicated. Once we decided to use a common structure we will stick to that and that makes structures more uniform and easier to predict. 

There are several common tasks, implemented once again:
- add and delete undoable operations
- indexing items for serialization, should rather not be part of the items
- substitution of indices by references during deserialization
- serialization and reserialization of the collection itself
