### ISSUE TITLE
JobsScheduler - preset dialog template

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#30]
Zvážit, popřípadě naimplementovat template, které zajistí jednotný vzhled, případně serializaci presetů v #27, #28, #29

**Comment by johnymachine** [comment]
Čeká se na implementaci zmíněných Issues a jejich abstrakci.
Zatím jsou presety celkem jednoduché a není to tedy nutné, případně lze použít libovolný předchozí a přepsat texty a signály.
