### ISSUE TITLE
Simplify LayerPanel

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/GeoMop#306]
Currently the implementation use two stage process:
- first assembling a list of model objects
- second creating the actual widget

Make the helper data structure (suited for the widget creation) 
together with the widgets.

**Comment by TomasBlazek1** [comment]
I tried to create the widgets as soon as I had enough information.

**Comment by TomasBlazek1** [comment]
Create small model objects to improve code structure and readability
