### ISSUE TITLE
Model Editor - Chyby a vylepšení

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#34]
[aktualizovano 16.10.2015 k verzi 0.1.0 --TK]

https://docs.google.com/spreadsheets/d/1czNMJsB8bu3kaa-gKFNQdUbUXgquoDzIscbWaarZ5sA/edit?usp=sharing

**Comment by jbrezmorf** [comment]
Souhlas s odstranenim funkce doplnovani mezer (bug 4).

Honza

On 08/26/2015 10:54 AM, Pavel Richter wrote:
> Rozhodnout se co s tím.
> https://docs.google.com/spreadsheets/d/1czNMJsB8bu3kaa-gKFNQdUbUXgquoDzIscbWaarZ5sA/edit?usp=sharing
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GeoMop/GeoMop/issues/34>.
> 

-- 
------------------------
Mgr. Jan Brezina, Ph. D.
Technical University in Liberec, New technologies institute
http://www.nti.tul.cz/cz/WikiUser:Jan.Brezina

**Comment by sha512rp** [comment]
Opraveno:
- e9: strom a dalsi panely nekradou focus z editoru
- e18: messagebox pro potvrzeni zmen ma focus i pri vyvolani pomoci klavesove zkratky
- e13: pro nove vytvarene polozky v poli se zobrazuje spravne info

**Comment by sha512rp** [comment]
Opraveno:

- e10, e11: oprava validace datoveho typu pro integer, double, bool
- e12: v clipboard zustane obsah i po ukonceni aplikace

@richtertul Bohuzel jediny zpusob, ktery jsem nasel, jak uchovat clipboard i po ukonceni aplikace, vyzaduje zavislosti na Python package `pyperclip`. Funguje multiplatformne, ale pod Linuxem potrebuje, aby system mel instalovany `xclip`. Otestoval jsem to pod Windows 10, Linux Mint 17. Updatoval jsem requirements.txt, a pro linux uvedl do dokumentace novou zavislost na `apt-get install xclip`. Pokud by to vadilo, tak muzu pokusit omezit to uchovani clipboard pouze pod Windows.

**Comment by sha512rp** [comment]
Opraveno:

- i4: lepsi viditelnost pruhu ve strom (vyraznejsi barvy + border)
- doplneni `.yaml` koncovky pri ukladani
- aplikace se nyni ukonci pri `Ctrl+C` z konzole

**Comment by sha512rp** [comment]
- [ ] pri kliknuti na error nebo tree posunou kurzor na zacatek misto na konec

**Comment by sha512rp** [comment]
Opraveno:

- e15, e23 - pri smazani nyni dojde korektne k refreshi
- e3 - odstraneno, uz to nezpusobovalo zadny problem

**Comment by sha512rp** [comment]
Opraveno:

- e19, e20, e21 - akce elementChanged, structureChanged se nyni spravne vyvolavaji
- e22 - odrazky pro polozky v poli se doplnuji, pokud je to zapnuto v nastaveni
- e25 - opravena napoveda pro transpozice
