### ISSUE TITLE
Model Editor - IST - JavaScript

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#35]
Rozchodit javascript na qt.

**Comment by sha512rp** [comment]
Javascript funguje. Problem je v generovani html v knihovne Flow123d-python-utils. Resim to s Honzou Hybsem.

**Comment by sha512rp** [comment]
Vyreseno, probehly zmeny v json formatu. S korektnim souborem se mi podarilo generovani zprovoznit.

Problem je, ze se rovnice generuji dlouho (u me ~4s) a mezitim zamrzne GUI. Na cas generovani nema vliv pocet rovnic - jedna trva zhruba stejne dlouho jako deset. Stejny kod se ve Firefoxu vygeneruje prakticky okamzite. Problem bude nejsis v `QWebKitWidgets.QWebView`. Jelikoz je `QWebKitWidgets` depracated, budouci verze to nevyresi. Resenim by mohlo byt zkusit novy `QWebEngine`. K nemu se mi zatim nepodarilo najit zadne examples a nevim, jak dlouho by to trvalo naimplementovat.

Prozatim nechavam veskere zmeny v branchi `info_webkit`, protoze do `master` nechci davat kod, ktery nefunguje prilis dobre.

**Comment by richtertul** [comment]
Zkusím se na to o víkendu podívat (jestli by mě něco nenapadlo).

**Comment by jbrezmorf** [comment]
Jestli tomu dobře rozumím, tak Honza Hybš používá KaTex pro generování HTML. Já jsem mu doporučoval MathJax, ten umí generovat výstup jak v javascriptu, tak v SVG.

**Comment by richtertul** [comment]
Vypadá to že problém není s renderováním rovníce, ale s jejím zobrazením. Možná se WebKitu nelíbí katex fonty. Zkus se podívat zda je nejde nějak WebKitu podstrčit jinou cestou. (Pokud by zpoždění bylo jen při prvním načtení, asi by to tolik nevadilo.)

Zkoušel jsem do main.js dát:
   var test = katex.renderToString(code);
    element.innerHTML = test;
a pokud zaremuji druhý řádek, vypadá čas OK. Vložit normální text do doomu je rychlé, ale strukturu jsem nezkoušel.

**Comment by sha512rp** [comment]
Problem je opravdu ve fontech a ne v javascriptu. At jsem zkousel KaTeX fonty naimportovat jakkoliv, vzdycky to trvalo dlouho. Problem je nejspis na strane webkitu, viz [tento prispevek](http://stackoverflow.com/questions/16999682/qtwebkit-take-eight-seconds-to-render-the-page-if-custom-fonts-are-used). Nicmene kdyz jsem nainstaloval Qt5.5 s nejnovejsi development verzi PyQt a sip, nacitani trvalo jeste dele.

Zkousel jsem pouzit MathJax, ten sice funguje rychle, ale ma to zase jine problemy. Pri nacitani se asi 3x zmeni element s rovnici a dochazi k takovemu vizualnimu jitteru, ktery pusobi dost rusive. Zkousel jsem to ruzne vyresit, ale zadne reseni nebylo dokonale. Navic samotny MathJax ma asi 60 MB. Aktualni priklad s MathJax je v branchi `info_mathjax`.

Nejpouzitelnejsi se prozatim ukazuje pouziti KaTeXu bez fontu. Vysledek sice nevypada tak pekne jako s fonty, ale osobne se mi to asi libi vic, nez to prekreslovani u MathJaxu. K dispozici v branchi `info_webkit`.

Jedine dalsi reseni, co me napada je zpracovani TeXu na urovni Pythonu. To ale neni moc trivialni. Sice lze jednoduse vygenerovat MathML, ale to zase nepodporuje WebKit. Pro generovani SVG by byla potreba distribuce TeXu, cimz se to znacne zkomplikuje.

Resim uz to celkem dlouho a nejak se porad nemuzu dostat k nejakemu rozumnemu reseni.

**Comment by richtertul** [comment]
Za mě řešení s normálníma fontama vypadá pro naše účely (testování obsahu) OK. Snad jen kdyby šel font s rovnicema o jedno zmenšit, ale kdyby to dělalo jiný problémy tak ne. Sluč to do masteru, ale branche nech. V budoucnu bude dost času si s tím hrát.

**Comment by sha512rp** [comment]
Pouzit KaTex bez fontu, slouceno do masteru.
