### ISSUE TITLE
Model Editor - IST - zobrazení hodnot

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#36]
Upravit stávající knihovnu tak aby zobrazovala potřebné hodnoty. (Designe se bude řešit později s tree.)

**Comment by sha512rp** [comment]
Upravil jsem, co se vypisuje pro record a selection. Info se aktualne da pouzit maximalne pro napovedu u jiz napsanych dokumentu, a i pro ne to neni optimalni.

Pro psani dokumentu to bude chtit celkem rozsahle zmeny. Souvisi to s detekci klicu, hodnot, tagu a mozna i referenci. Napr:

    problem: !SequentialCoupling
        ^    ^                   ^
        1    2                   3

Na techto mistech by se mely zobrazovat jine info texty. Podle me tyto:
1. `Root`(Record) s vybranym klicem `problem`
2. `Problem`(AbstractRecord), kde bude seznam implementaci
3. `SequentialCoupling`(Record) bud bez klic, nebo s vybranym defaultnim/prvnim

    mesh:
    ... (mezery)
    ^ ^
    4 5

Zde bych vypisoval info podle pozice kurzoru - urovne vnoreni.
4. Record nadrazeny klici `mesh` a napovidat jeho sousedy
5. `Mesh`(Record), napovidat jeho potomky

Nesouvisi to tedy jen s info textem, ale i s autocomplete. Cele by to chtelo promyslet a udelat nejakou dobrou implementaci, ktera nebude vracet jen `DataNode` - to je pro nas nedostacujici. Potrebujeme zjistovat info a options na konkretni pozici v ramci DataNode. Je to pomerne slozita funkce a nechtel bych to uspechat, protoze to povazuji za celkem zasadni.

**Comment by richtertul** [comment]
Ok, na to pak udělám nový task
