### ISSUE TITLE
Model Editor - Historie

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#37]
- prozkoumat jak překlenout historii přes SetText funkci Scintilla editoru a implementovat. ( V krajním případě, pokud by to nešlo jinak, udělej vlastní funkci, která udělá diff a insertuje, popřípadě smaže změny, tu pak strčíme místo SetText, kde bude potřeba )
- pomocí beginUndoAction(), endUndoAction() udělat historii po refreshích
http://pyqt.sourceforge.net/Docs/QScintilla2/classQsciScintilla.html
- přidat undo a redo do menu.

Tasky #37,#38,#39 si asi první přečti a udělej společný průzkum co umí scintilla. Dokumentace není vyčerpávající a možná budeš hledat i jinde, ale může to ušetřit hodně času.
http://pyqt.sourceforge.net/Docs/QScintilla2/annotated.html

**Comment by sha512rp** [comment]
Implementovano.

Aby se dalo undo/redo pouzit pri psani, je potreba:

- odstranit tu fci co obcas automaticky prida mezeru. Behem prochazeni undo/redo sekvence dojde obcas k jeji aktivaci a tim sekvenci prepise a uz nejde redo
- vylepsit, kdy dojde k reloadu (hlavne tagy, zacatky klicu, odsazeni, konec obsahu)
- nejak jinak vyresit reload pri fatal erroru, takhle to funguje po znacich
