### ISSUE TITLE
Model Editor - Find, Replace Dialog

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#38]
Přidat do dialogs adresáře dialogy pro hledání a nahrazení. Dialog se objeví na dané pozici Yaml editoru (asi v pravo nahoře, ale je to jedno), bide nemodální a vždy na vrchu. Implementaci i funkce je dobré převzít z něčeho, kde to funguje dobře. Operace si bude možné napojit na stávající funkce scintilla editoru. http://pyqt.sourceforge.net/Docs/QScintilla2/classQsciScintilla.html Scintila umožnuje i reguláry. Tak by to tam mohlo být taky, (Pokud s tím nebudou problémy)

**Comment by sha512rp** [comment]
Find dialog a funkce implementovany, nahrazeni snad stihnu dodelat v pondeli.

**Comment by sha512rp** [comment]
implementovano 6b538fd3b322ce7b0f307861b685fd170b1a565f
