### ISSUE TITLE
Model Editor - Edit operace

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#39]
Přidat do menu co nejvíce operací jako je copy, paste, comment, itend, .... Hodně z toho podporuje scintilla http://pyqt.sourceforge.net/Docs/QScintilla2/classQsciCommand.html . Myslím že by to mělo jít napojit nejen na klávesy, ale i na menu. Příkazům přiřadit i obviklé klávesové zkratky,

Indent je http://pyqt.sourceforge.net/Docs/QScintilla2/classQsciScintilla.html a možná i něco dalšího. Ale radši prohlídni celou dokumentaci.

**Comment by sha512rp** [comment]
Funkce:
- undo
- redo
- cut
- copy
- paste
- delete
- select all
- indent
- unindent
- comment

Pridano do menu, kontextoveho menu a do klavesovych zkratek.

**Comment by richtertul** [comment]
Ještě mi tam chybí uncomment.

**Comment by sha512rp** [comment]
Comment funguje jako toggle - pokud jsou vsechny radky zakomentovane, komentar se odstrani
