### ISSUE TITLE
JobsScheduler - Add new Resource (dialog)

### ISSUE THREAD

**Issue by johnymachine** [GeoMop/GeoMop#40]
Vytvořit dynamického GUI průvodce, který nastaví Resource v několika režimech.
(Lokálně, Vzdáleně, Vzdáleně jen výpočty, atd.)

**Důraz na názornost a použitelnost, zvážit ilustrativní obrázky, případně krokový wizard.**

**Comment by jbrezmorf** [comment]
Myslím, že GUI pro kongifuraci Resource může být zatím poměrně nepřívětivé. Teprve se bude zjišťovat co všechno bude potřeba konfigurovat. Navíc i do budoucna je předpoklad, že konfigurace REsource budou dělat jen "poučení uživatelé".
