### ISSUE TITLE
JobsScheduler - Serializace dat  z formulářů

### ISSUE THREAD

**Issue by johnymachine** [GeoMop/GeoMop#41]
Jednotlivé serializace přidány do vlastní Issue.

**Comment by johnymachine** [comment]
@richtertul 
Koukám na tu serializaci, úplně tomu však nerozumím.

Mohu poprosit o příklad jak si uložit vlastní list a opět ho načíst,
Je to list listů jako záznamy.

```python
mylist = list()
mylist.append(list())
mylist.append(list())
```

**Comment by richtertul** [comment]
import config as cfg
# uloží do {geomop data addr}/mj/list.yaml
# zatím {geomop data addr} = GeoMop/Config  
cfg.save_config_file("list", mylist,"mj")
mylist=None
# vyzvedne mylist 
mylist = cfg.get_config_file("list","mj")

**Comment by johnymachine** [comment]
@richtertul 
Nedaří se mi správně importovat v JobsScheduleru tento soubor není a ModelEditor je vedlejší adresář, který jako by nevidím?

**Comment by johnymachine** [comment]
# SSH Presets data
| Id (hidden) | Name        | Description (autogenerated) | Host              | Port | User | Password |
|-------------|-------------|-----------------------------|-------------------|------|------|----------|
| 16fd2706    | MetaCentrum | host:port, user             | meta.cesnet.cz    | 22   | User | Passwrod |
| 16ce2706    | Ostrava     | host:port, user             | ostrava.cesnet.cz | 22   | User | Password |

**Comment by johnymachine** [comment]
@sha512rp pochopil jsem správně, že se konfigurace cfg přesunula do home?

Pokud ano tak všechny ostatní jsou složky lowercase, možná by stálo za to se toho držet. (Jinak by mohl možná nastat problém s case na windows.) => předělat na lowercase?

**Comment by sha512rp** [comment]
Slozku pro ukladani konfigurace jsem presunul kvuli instalaci GeoMopu. V linuxu se pouzije `~/.GeoMop` a na Windows `%APPDATA%\GeoMop`

Konvence v linuxu je asi spis .lowercase, ale treba zrovna pycharm pouziva `.PyCharm`. Za me je to jedno - drzel jsem se toho, jak mame pojmenovany github.

**Comment by johnymachine** [comment]
Ok tak je to asi jedno a problém to nedělá =)

**Comment by jbrezmorf** [comment]
Kdyz se kouknu u sebe na ~/.* tak vidim pouze dva adreare obsahujici uppercase.  Pro lowercase mluvi dva duvody: 
1) lepe se to pise a pamatuje
2) odpadnou pripadne zmakty pod Windows, jelikoz tam myslim stale plati ze geomop a GeoMop a GEoMoP je ten samy soubor.

**Comment by jbrezmorf** [comment]
Predpoklada se pro GeoMop fixni workspace? Tedy jeden adresar s projekty? V opacnem pripade by mohly byt projekty kdekoliv i napr. na odpojitelnem disku a to by znamenalo vsechna data stazena asynchronne z metacentra ukladat do konfigurace a to bych nerad.

**Comment by richtertul** [comment]
config - data specificke pro installaci
workspace - data nezávislá na instalaci (zatím jsem moc neřešil)
Nejsem si zcela jist kam patří MultiJob data zatím jsou v configu. Jsou tam i data specifická pro installaci a například hesla by neměla být ve workspace. V budoucnu nevylučuji že bude potřeba udělat nějaký import/export, popřípadě rozdělení a částečný přesun do workspace, ale myslím že ted je to předčasné a musí tomu předcházet nějaká diskuze.
