### ISSUE TITLE
Model Editor - IST - zohlednění pozice

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#42]
V yaml editoru je připravena událost 
elementChanged(int nova_hodnota, int stara_hodnota)
a funkce
int hodnota = get_curr_element_type()
které vracejí:
    key = 1
    tag = 2
    ref = 3
    anch = 4
    value = 5
    other = 6
Je potřeba udělat logiku do model_editoru a pokusit se reloadnout, pokud je to potřeba, IST. Myslet na to že v budoucnu zde asi bude napojeno i našeptávání. (pokud by to bylo málo práce, tak ho tam připojit hned)
Pokud budeš potřebovat i funkci, která vrátí i hodnotu elementu, napiš, dodělám.

**Comment by sha512rp** [comment]
Info nyni zohleduje pozici kurzoru. Udelal jsem jeste vylepseni souvisejici s autokonverzemi a abstraktnimi zaznamy. Info je ted pouzitelne, pokud se prozkoumava/modifikuje existujici konfiguracni soubor. (Pro vytvareni budeme muset udelat jeste tu predikci.)

@richtertul 
Nasel jsem jeste jeden bug. Pri kliknuti na prvni klic v zaznamu nedojde k udalosti `nodeChanged`, pokud na ten klic kliknu z nadrazeneho zaznamu.

1. otevrit `flow_implicit_fields_gmsh.yaml`
2. kliknout na klic `problem`
3. kliknout na klic `description` - tady by melo dojit u udalosti `nodeChanged`, ale nedojde
4. kliknout na klic `mesh` - dojde k udalosti, jak by melo
5. kliknout opet na klic `description` - nyni uz k udalosti dojde

Bug se vyskytuje i u dalsich zaznamu, napr. `primary_equation -> output` nebo `output -> output_streams`.
