### ISSUE TITLE
GeoMop - Build window instalačky

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#44]
- NSIS 
- Co půjde nainstalovat v tichém režimu z exe, zbytek pipem
- Nakopírovat ze src (V ideálním případě označené moduly)
- verzi vzít z .version a nakopírovat do installatoru

**Comment by sha512rp** [comment]
Funkce instalatoru:

1. vse funguje offline, zadne zavislosti se nestahuji z internetu
2. detekce Python 3.4 32b: pokud neni nalezen - nabidne klasickou instalaci Pythonu (Nedoporucuji silent mod, mohlo by dojit k prepsani existujiciho Python 64b - pouzivaji stejnou cestu. Navic Python je samostatna vec, ktera se i samostatne musi odstranit pri odinstalaci. Je to z toho duvodu, ze Python muze byt sdilen vice aplikacemi.)
4. spusteni instalatoru GeoMop - vyber komponent
5. vytvoreni virtualniho prostredi pro Python - nedojde ke kolizi packagu, pokud uzivatel pouziva Python i pro neco jineho
6. prekopirovani zavislosti - Python package + PyQt5 (PyQt5 se neinstaluje -> toto reseni zajisti, ze uzivatel muze mit nainstalovano PyQt4, ktere muze byt vyzadovano jinymi aplikacemi nebo uzivatelem.)
7. vytvoreni odinstalatoru, zastupcu (odinstalace odstrani vsechno, krome samotneho Pythonu, viz vyse)

Testovano pod:
- Windows 10 Pro 64b
- Windows 7 Professional 32b
- Windows XP SP3 32b

Aby sel vytvorit Windows build, je potreba mit specialne nakopirovane zavislosti ve slozce build/win_x86 - hlavne pro PyQt5. Ma to asi 120MB, nevim jestli to davat do gitu, nebo spis vytvorit nejaky postup ve vyvojarske dokumentaci.

Instalator pro 64b jsem zatim nevytvarel. Pokud ho budeme chtit, melo by to by byt maximalne na par hodin.

Testovaci instalator [zde](https://drive.google.com/open?id=0B6-TS7AvXjTcTXNZT1EwbHllSE0).
