### ISSUE TITLE
Model Editor - Tree

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#45]
Prozkoumat grafické možnosti tree wiev (css)

**Comment by sha512rp** [comment]
Povedlo se mi zjistit, jak zmenit sirku odsazeni - nejde to pres CSS, ale slouzi k tomu `setIndentation`. Vytvoril jsem vlastni ikony, aby to slo zmensit a vypadalo to tak, jak ma.

- Navrhovane reseni: 12px bez rootu (nektere sipky jsou prilis blizko okraji okna, chtelo by to okraj)
![image](https://cloud.githubusercontent.com/assets/10220243/9883571/1d6e10fa-5bdb-11e5-8c71-dddbf0c631e0.png)

- Puvodni strom: 20px s rootem
![tree_original_20px_root](https://cloud.githubusercontent.com/assets/10220243/9883636/7fb6a15a-5bdb-11e5-82ab-984d45e9060f.png)

Dalsi alternativy:

- 12 px s rootem (celkem resi ten problem s okrajem okna oproti variante bez rootu)
![image](https://cloud.githubusercontent.com/assets/10220243/9883656/a4329a0c-5bdb-11e5-8465-0f5af700ac29.png)

- 10 px, na hranici pouzitelnosti
![image](https://cloud.githubusercontent.com/assets/10220243/9883661/a7788bea-5bdb-11e5-8364-9dd92e287c27.png)

- 8 px minimum, co se da zobrazit - podle me uz prilis male
![image](https://cloud.githubusercontent.com/assets/10220243/9883663/aa5fdbd8-5bdb-11e5-96d0-ca7f7db4a8be.png)

**Comment by richtertul** [comment]
Mě se zdá teda dobrá i 10. (Jsou tam menší šipky, nebo se mi to zdá?) Možná kdyby tam šlo udělat 11,12 s menšíma šipkama. Ale ten okraj tam opravdu chybí. Otázka je zda kvůli tomu dělat rozbalovací root, pokud jeho sbalení je spíš na škodu. Myslíš že to nepůjde odsadit?

**Comment by jbrezmorf** [comment]
Navrhuju zatim zkusit 10px s rootem a uvidi se zda to bude pouzitelne.

**Comment by sha512rp** [comment]
Do `master` jsem dal verzi 10px s rootem.
![image](https://cloud.githubusercontent.com/assets/10220243/9914541/a735a79e-5cb2-11e5-8b1f-9853838915d8.png)

@richtertul 
Sipky jsou u 12 px vetsi, Qt si ty obrazky prekresli, jak potrebuje. Proto taky ty obrazky, co jsem vytvoril nejdou pouzit pro lichy pocet px, dojde k takovemu nepeknemu aliasingu. Musel bych zas ty obrazky predelat pro jiny rozmer.

Pokud se nepouzije odsazeni rootu, tak pres CSS tam muzu doplnit padding, ale ten odsadi i zahlavi stromu. Pokud to zahlavi bude slouzit pouze kosmeticky a nebude mit zadnou funcknost, mohli bychom ho ze stromu odstranit, strom odsadit, a v nadrazenem layoutu pridat nejake komponenty, ktere by slouzily jako zahlavi.

![image](https://cloud.githubusercontent.com/assets/10220243/9914543/a84857da-5cb2-11e5-9d58-1019c03870ab.png)
