### ISSUE TITLE
Import složky lib

### ISSUE THREAD

**Issue by johnymachine** [GeoMop/GeoMop#47]
# Import složky lib

V Pycharm stačí pravým / Mark Directory As / Sources Root

To ale asi nebude fungovat globálně.

**Současné řešení**
```python
import os
import sys
__lib_dir__ = os.path.join(os.path.split(
    os.path.dirname(os.path.realpath(__file__)))[0], "lib")
sys.path.insert(1, __lib_dir__)
```

**Funkční ekvivalent**
```python
import sys
sys.path.append("../lib")
```

@richtertul Nestačí to takto?

**Comment by richtertul** [comment]
1. Nebude to fungovat na windows
2. Asi bych zůstal u plné cesty, kdyby někdo měnil app adresář

**Comment by johnymachine** [comment]
```python
import sys
import os
sys.path.append(".." + os.pathsep + "lib")
```

1. Vyhodnotí jako absolutní cestu do `sys.path`
2. S `os.pathsep` by mělo fungovat i na win.

Neměl by tedy být poznat rozdíl...

**Comment by johnymachine** [comment]
Zůstáváme u původního řešení
