### ISSUE TITLE
Model Editor - Přehled chyb

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#48]
- Udělat přehled chyb zobrazovaného Yamlu a přiřadit jim čísla 100-999
- Néjlépe samostatný soubor ve formátu například mapy, který je použit i jako zdroják. Příklad, kterého se není nutné držet:

parsing_error = 
{
  # krátký popis
  "name": [cislo, text],
  ..
}

**Comment by sha512rp** [comment]
Vytvorene soubory `example_*.yaml` v `samples/ModelEditor/YamlFiles` s ukazkami chyb, ktere mohou nastat.

`ErrorHandler` predelan na `NotificationHandler` + propojeni se seznamem vyjimek `helpers.notifications.list`
