### ISSUE TITLE
Model Editor - Drobné issues + Errors

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#51]
- gimp soubory přesunout z src
- odstranit mezery z historie
- debug do args - schovat debuf + json editor
- chybné ist pro bc_types
- posunout konečnou pozici pro posledni node

**Comment by sha512rp** [comment]
@richtertul K te konecne pozici posledniho node - je potreba opravdu upravit primo `node.span`? Pokud je nakonci napriklad nejaky skalarni node, tak to pak bude problem napr. pri oznaceni nodu. Nestacilo by pouze upravit `DataNode.get_node_at_position`?

**Comment by richtertul** [comment]
Na tohle jsem ti již odpovídal, ale nevidím to, jako bych to špatně odeslal. Psal jsem, že je jedno jestli bude nová řádka, pozice za koncem řádky, nebo upravená funkce. Lepší je pokud by chování bylo konzistentní s prvkama uvnitř struktury.

Ale asi je to jedno, protože potřeba tohoto byla způsobena asi načítáním upravovaného nodu ve staré struktuře pomocí pozice z upravených dat. To jsem opravil a uvidí se jestli to nebude stačit.

Udělal jsem úpravy pro přidávané řádky. Chová se to lépe, ale ještě to asi není ono. Kdyby si se na to mohl podívat a napsat mi co se podle tebe zobrazuje v ist chybně. Testoval jsem to, ale nějak se ztrácím v tom co se má zobrazovat. Kdyžtak si pak zavoláme a probereme co s tím.

Dále by chtělo zajistit, aby se při startu editoru s prázným dokumentem zobrazila nápověda k rootu.

**Comment by sha512rp** [comment]
- root info_text se nyni zobrazi po startu
- vypada to, ze uprava span u posledniho nodu uz neni nutna - rad bych se tomu vyhnul, pokud to neni nutne delat
- zobrazovani IST jeste otestuju a zitra napisu mail
