### ISSUE TITLE
Model Editor - tag v tree

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#52]
Zobrazovat typ abstractu v tree

**Comment by sha512rp** [comment]
Pro AbstractRecord se nyni v tree zobrazuje barevne odliseny type ve sloupci pro value.

@richtertul Pro polozky v poli se nyni po kliknuti ve strome pouzije `node.delimiters` pro `itemSelected`. Zatim jsem ale vzdycky narazil na to, ze `node.delimiters` je `None`.

**Comment by richtertul** [comment]
opraveno
