### ISSUE TITLE
Model Editor - zobrazení nodu z editoru ve stromu

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#53]
Při kliku na číslo řádku, zobrazit node ve tree. Zobrazí se node ke kteremu patří první neprázdný znak na řádku.

**Comment by sha512rp** [comment]
- prislusny node se zobrazi v tree
- prazdne radky a radky, kde je pouze komentar se ignoruji
- hidden nody se ignoruji
- po kliknuti se Qt pokusi strom vycentrovat (scroll) na vybrane polozce
