### ISSUE TITLE
Model Editor - zalozky v ist

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#55]
Zprovoznit záložky v ist

**Comment by sha512rp** [comment]
Design IST helpu kompletne predelan podle navrhu Honzy. Klice jsem misto zobrazeni pod sebou zobrazil jako dlazdice - usetri to spoustu vertikalniho mista. U `Selection` jsem musel trochu improvizovat, pokud by se to melo zobrazovat jinak, tak se to kdyztak doladi.

Zprovoznil jsem i klikani na klice, hodnoty selection a implementace abstraktnich zaznamu. Pripravil jsem to tak, aby sla dodelat historie (vsechno jsou dotazy pres GET), ale samotnou historii jsem zatim neimplementoval.

Spolu s tim se mi povedlo i odstranit chyby, diky kterym se zobrazovala obcas odlisna napoveda pri kliku mysi vs posunu sipkami na klavesnici.
