### ISSUE TITLE
Model Editor - IST navigace

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#57]
- Možnost odkazů v IST
- Dodělat historii 
- Pokud se použije odkaz, v pravém horním rohu bude umožněno skočit na původní nápovědu, na předchozí a na další (Asi bych to udělal tak že navigace se zobrazí při prvním kliku na odkaz a pak tam budou vždy tři ikony, origin zašedlá pokud se někdo vráti na začátek, back  zašedlá pokud nepůjde zpět a next  zašedlá pokud nepůjde napřed)

**Comment by sha512rp** [comment]
implementovano v fe61afed9db2aba33ab887edd87add54348006f3
