### ISSUE TITLE
Model Editor - Bublinková nápověda - seznam tagu a kotev

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#59]
- zavisi na #61
- Přidat do nápovědy odpovídající položky začínající ! a * pro tagy a odkazy 
- Asi bude nutné (stačit) přidat do value (vyzkoušet)

**Comment by sha512rp** [comment]
Aktulane to funguje nasledovne:
- anchory se zorazi v autocomplete vzdy, ale jako posledni
- tagy se zobrazi pro AbstractRecord i pro konkretni implementaci - tedy Record; tagy se zobrazuji ke konci, tesne nad anchory

Optimalni reseni by bylo to filtrovat podle napsaneho retezce a zobrazit anchory, jen pokud uzivatel zada '*' a obdobne s tagy. Tohle reseni by bylo pomerne slozitejsi.

Pokud by ten soucasny system nevyhovoval, bylo by to mozne predelat. Hlavni nevyhodu asi vidim v tom, ze anchory se zobrazuji i pokud je to to jedine, co se muze zobrazit. Z pohledu YAMLu to ale dava smysl, protoze anchorem muze byt cokoliv a tedy to muze i kdekoliv pouzito.
