### ISSUE TITLE
Model Editor - Bublinková nápověda - přidání klíče

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#60]
- zavisi na #61
- udělat seznam child klíčů a přidat jej do nápovědy
- prozkoumat, zda jde udělat po výběru položky z bublinkové nápovědy nějakou akci, například po výběru klíče z bublinkové nápovědy přidat za klíč dvojtečku  (udalost QScintilla?)
- pokud to nepůjde, dát dvojtečku za klíč v node.options

**Comment by sha512rp** [comment]
Vyreseno. Klice se zobrazuji v napovede bez `: `, ale pridaji se vcetne.
