### ISSUE TITLE
Model Editor - Bublinková nápověda - předělat node options

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#61]
Ted funguje bublinková nápověda tak, že se ve funci yaml_editoru pos._reload_autocompletation nahrají texty z node.options. Což není štastné:
- nepůjde nápověda pro nové prvky
- pamětově náročné
- nezohlední se cursor possition
Udělat mechanismus podobný nahrávání IST, který po změně nodu a typu cursoru udělá reload nějakého parametru options v meconfigu a uloží tam potřebnou nápovědu. Předělat pos._reload_autocompletation aby se nahrál správný seznam. Udělat zatím dva seznamy (pro key a value) a podle pozice kurzoru je prohazovat. Uvidíme jak to bude fungovat. Pokud by byl problém, udělat zatím jen jeden velký složený z obou a já se podívám co je potřeba upravit.

**Comment by sha512rp** [comment]
Vyreseno - komponenta `AutocompleteHelper`.
