### ISSUE TITLE
Model Editor - IST- přidání akce do menu k odkazu 

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#63]
Prozkoumat a případně přidat položku "copy to editor" do IST menu, zobrazeného při kliku pravím tlačítkem na odkaz.

**Comment by sha512rp** [comment]
Implementovalo by se to celkem slozite a asi by to ani nemelo vyuziti s tim, jak ted funguje autocomplete. V souvislosti s tim jsem odebral kontextove menu, protoze nenabizelo zadnou pouzitelnou funkci.

**Comment by jbrezmorf** [comment]
Myslim, ze nejake ty funkce do IST kontextoveho menu casem jeste najdeme.
