### ISSUE TITLE
Model Editor - Dialog Settings

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#66]
Do benu přidat settins a dialog který mu odpovídá. 
Dialog bude mít dva Taby
- [x] klávesové zkratky - které umožní zadat zkratku pro vyvolání kontextového menu a další použité
- [x] common, kde bude možno zapnout autocomplete
Budou doimplementovány věci návazné na obojí

**Comment by sha512rp** [comment]
Settings dialog hotovy.

U tech klavesovych zkratek jsem uz nestihal to poradne otestovat a neosetroval jsem pripady, kdy tam uzivatel zada jako klavesovou zkratku napr. pouze jeden znak ('A') - potom by v editoru pochopitelne nesel napsat znak A, protoze by to byla zkratka.

Take je pro aktualizaci zkratek ve vsech menu potreba restartovat aplikaci. Vzhledem k tomu, ze klavesove zkratky se zas nemeni tak casto bych to takhle asi nechal, nez resit kde vsude je potreba zkratky aktualizovat a kdy.

Ukladani zkratek i nastaveni je pomoci Configu.
