### ISSUE TITLE
Model Editor - Bublinková nápověda - autocomplete

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#69]
Návrh implementace:
Udělat strukturu ccontext s proměnnými:
- word - slovo pro doplnění
- possition - pozice slova v editoru 
- cursor - pozice cursoru ve slově

Dodělat statickou funkci get_ccontext do subyaml.lineAnalizer s parametry line(text), possition(cursor), která vrátí hcontext (word může být prázdné)

Udělat autocomplete_helper stavový, aby si pamatoval pozici slova a zda je zobrazováno našeptávání, věděl zda provádět autocomplete a použival ccontext. Navrhuji následující funkce:
- set_completation(ccontext) která zapne našeptávání a vrátí array slov k našeptávání nebo None   
- refresh_completation(ccontext) ta:
    - zkontroluje zda se jedná o shodný context (podle pozice slova), pokud ne vypne našeptávání, jinak vrátí array slov k našeptávání nebo None
    - pokud jde o nový context pak v případě zapnutého autocomplete, délky slova větším než 1 a neprázdného listu zapne našeptávání a vrátí array slov k našeptávání
    - jinak vrátí None
- stop_completation()
- get_completation(ccontext) - vrátí slovo pro doplnění, nebo None

Použití autocomplete_helper (vhodně strukturovat do funkcí a zařadit do yaml editoru)
  - ctrl+mez zjistí ccontext z lineAnalizer.get_ccontext seznam, z set_completation a zobrazí nápovědu (dále pokud funkce vrátí None, nápověda je schována)
  - esc zavolá stop_completation a schová nápovědu
  - enter, tab  zjistí ccontext z lineAnalizer.get_ccontext, seznam zavolá get_completation, stop_completation, doplní a schová nápovědu
  - ve funkci _cursor_position_changed (asi nakonci) zjistí zda je zapnuté našeptávání a pokud ano zjistí ccontext z lineAnalizer.get_ccontext seznam, pomocí refresh_completation zjistí zda schovat nebo updatovat nápovědu a pokud ano zavolá stop_completation a schová nápovědu

**Comment by richtertul** [comment]
Nějak jsem to včera nedomyslel.Ty potřebuješ vědět kdy autocomplete zapnout a to je ve funkci _text_change. Asi bych v autocomplete_helper, pokud je našeptávání vypnuto, nahodil nějakou stavovou proměnnou autocomplete_pending na True. Akci ve funkci _cursor_position_changed bych udělal pokud je našeptávání zapnuto a nebo autocomplete_pending je True. V této akci by se mělo zapnout našeptávání pro autocomplete_pending True jen v případě kdy word obsahuje jedno písmeno a existuje nápověda. Pak autocomplete_pending vrátit na False.

**Comment by sha512rp** [comment]
Pridana funkcnost pro zuzovani moznosti autocomplete pri psani + moznost volby automatickeho zobrazeni autocomplete (zapnuti/vypnuti pridam do Settings).

Jeste se musim podivat na bug, ktery souvisi s refreshem, resp detekci hranic (uz jsme to resili). Krome toho by vsak mel byt autocomplete hotovy.
