### ISSUE TITLE
Model Editor - error array

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#7]
Dodělat errory
  - severity (info,warning,error)
  - začátek a konec bloku
  - vytvořit yaml sample file, kde budou všechny tři typy errorů

**Comment by sha512rp** [comment]
Nakonec jsem nasel vyuziti pouze pro warning a error.
Konec bloku jsem zatim nepridaval.
Je potreba upravit pocatecni pozici u nekterych erroru (unknown key, missing key, ...), aby neukazovali na pozici hodnoty, ale na pozici klice.
