### ISSUE TITLE
Model Editor - Dokumentace, refactoring

### ISSUE THREAD

**Issue by sha512rp** [GeoMop/GeoMop#70]
- [x] predelat `getcwd()` na absolutni cestu
- [x] dodelat dokumentaci pro pre-push + nahrat do gitu
- [x] dopsat dokumentaci parametru u ChangeAnalyzer, EditorPos
- [x] LineAnalyzer factoring (testy + dokumentace)
- [x] presunout prislusne metody z editoru do LineAnalyzer
- [x] cesta k CSS pomoci Qt (vyreseno pres doplneni absolutni cesty ke slozce resources po nacteni stylesheetu)
- [x] ~~odkaz k subdokumentacim otevrit v novem okne~~ (neni potreba, pridana navigace zpet na index)
- [x] odkaz k indexu dokumentace?
- [x] dokumentace - odkaz na transformace

**Comment by richtertul** [comment]
Prosimtě Honza by chtěl následující adresu někam na hlavní stránku, jako transformace, mohl by jsi to někam strčit:
http://geomop.github.io/GeoMop/aut/ModelEditor/data.yaml.html#module-data.yaml.transformator
dík

**Comment by sha512rp** [comment]
@richtertul Muzu uz upravit a pripadne presunout ChangeAnalyzer a EditorPos, nebo mas v planu jeste nejake zmeny?

**Comment by richtertul** [comment]
už můžeš, nebylo to potřeba.
