### ISSUE TITLE
GeoMop - logování

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#77]
- vytahnout debug a logování do nějakého souboru v common, musí to fungovat pro celý geomop jednotně
- z debug se musí vyhodit logging.basicConfig a musí se získat pomocí logging.getLogger(Geomop + "-" + modul), kde modul bude název programu, například ModelEditor. Logování pak půjde do souborů také po modulech
- při debugu mi applikace díky logování nespadne, což mě velmi zdržuje, ještě to proberem, zatím jsem při debugu logování vypnul. Pokud to nevadí, rád bych to tak nechal
- nelíbí se mi že applikace po zalogování pokračuje jako by nic. I kdyby měla spadnout, tak je to lepší než tohle, minimálně musí vyhodit nějaké okno, ještě se o tom pobavíme

**Comment by sha512rp** [comment]
- zachyceni vyjimky pri debug: IDE asi pouzivaji take sys.excepthook, takze kdyz to pouziju na logovani nezachycenych vyjimek, tak potom se neodchytnou v IDE; nechal bych to tedy tak, ze pokud se app pousti s parametrem --debug, tak je logovani vypnute (a tim padem funguje odchyceni vyjimek v IDE)
- ukonceni resp. neukonceni aplikace pri vyjimce neni ovlivneno tim logovanim; nekdy to spadne, jindy ne (asi v zavislosti, ve ktere casti kodu k vyjimce dojde - bud se Python zotavi, nebo ne). Udelal jsem v logovani callback, ve kterem je mozne bud zobrazit okno s chybou (tak jsem to zatim udelal) a nebo aplikaci shodit pomoci sys.exit() - ale to mi prijde moc drasticke, pokud je Python schopny se z chyby zotavit

**Comment by sha512rp** [comment]
71b98501dede1bb05c427bbffd48b40c9bc55c9c Logovani pridano do JobsScheduleru.

@richtertul Zkontroluj prosim, jestli JobsSchduler porad funguje, jak ma. Pro logovani by se to melo chovat stejne jako ModelEditor (pro zachyceni vyjimek v IDE je potreba to spustit s --debug).

**Comment by richtertul** [comment]
Zkontroluju to, jen prosímtě udělej:
 - druhou možnost předělej na to, aby to zobrazilo hlášku "Applikace provedla neplatnou operaci: " + vyjímka a spadla sys.exit(), to připoj na JobsScheduler (chci to mít pod kontrolou a data jsou v souborech)
 - u tebe to nech tak jak myslíš, jen bych tam udělal aspon nějaký reload, aby text z editoru odpovídal tomu ostatnímu a bylo to v konzistentním stavu (jen je tu nebezpečí že by to mohlo spadnout několikrát po sobě -), takže to musí být v try a pokud to spadne tam, tak schodit předcházející možností) Asi bych to řešil  předáním zotavovací funkce definované vně, tvojí třídě a jejím spuštění v try bloku

**Comment by sha512rp** [comment]
Upraveno.

- JS pri neodchycene vyjimce zobrazi error zpravu a potom spadne.
- ME se pri chybe pokusi o reload dat, pokud se nepovede, tak zobrazi hlasku a aplikace skonci; pokud k reloadu dojde bez chyby, tak pouze zobrazi hlasku o neodchycene vyjimce
