### ISSUE TITLE
GeoMop - Windows Install

### ISSUE THREAD

**Issue by sha512rp** [GeoMop/GeoMop#78]
- [x] umoznit reinstall - smazat vsechny stare soubory
- [x] pri pristi instalaci smazat predchozi konfiguraci! (zmena data.meconfig na meconfig.meconfig -> nelze spustit aplikace bez smazani konfigurace)
- [x] zmenit cestu configu na ModelEditor/
- [x] podivat se, zda QScintilla podporuje nejaky hezci font pod Windows - Consolas pro Win10
- [x] opravit chybejici css pro tree pod windows
- [x] odstranit pyperclip bug pod Win XP, kvuli kteremu applikace nelze spustit
- [x] opravit bug, ktery zamezuje smazani radku pod windows (nejspis CR LF vs LF)
- [x] updatovat changelog

**Comment by sha512rp** [comment]
@richtertul Zmenil jsem cestu ke configu u ModelEditoru, ale u JobsScheduleru jsem to nechtel menit, abych vam nerozhazel nacitani te konfigurace. Mozna by to ale bylo dobre taky to dat do samostatne slozky.

Nevedel jsem, zda presouvat i logy - zatim jsem je nechal primo v rootu app_data.

Mam pridat nejakeho zastupce do nabidky start pro otevreni logu, nebo je to zbytecne?

**Comment by richtertul** [comment]
OK, asi to uděláme taky. Zástupce zatím nedělej, ale není to tak špatný nápad. Možná bych to přesunul do log adresáře a dal bych tam celý log adresář, ještě to proberem.

**Comment by sha512rp** [comment]
- [ ] podivat se, zda QScintilla podporuje nejaky hezci font pod Windows

**Comment by sha512rp** [comment]
Pod Windows je nutne spoustet aplikaci ze spravneho pracovniho adresare - opet kvuli nacitani css (resp obrazku do nej vkladanych pomoci `url()`). Snazil jsem se to vyresit jinak, ale nepovedlo se mi to. Pod Linuxem je to mozne spustit odkudkoliv.

Pro drtivou vetsinu uzivatelu to asi neznamena vubec nic, protoze zastupci se vytvori tak, aby se to poustelo spravne. Pouze pokud by to nekdo poustel pomoci prikazu python a mel nastaveny jiny pracovni adresar, tak proste ve stromu nebude mit spravne obrazky.
