### ISSUE TITLE
Model Editor - chyby z testování

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#82]
- [x] otestovat jak se chová editor v případě že je na místě kde je očekáván string číslo, popřípadě float; zkonvertovat na string
- [x] otestovat editor jak se zachová, pokud budou v načteném dokumentu taby (kontrola, zda konverze neprobehne automaticky)
- [x] v popisu chyb místo 'TYPE' používat 'type (yaml tag)'
- [x] v nápovědě odlišit typem písma, nebo barvou typy klíčů (obligatory,...)
- [x] zkontrolovat chyby v example_complex_record_key (prebytecny warning o fatal_error)
- [x] pokud se v souboru example_merge smaže text za * na řádce 18 a klikne se jinam, program zamrzne (skončí v yaml/loader ve funkci _merge_into_node s temp==None )

**Comment by sha512rp** [comment]
Editor absolutne nepodporoval odsazeni pomoci `Tab` a pri prvnim takovem odsazeni doslo k fatal erroru. Upravil jsem to tak, aby se po nacteni zkonvertovaly taby na 2 mezery.

**Comment by sha512rp** [comment]
Pisma pro typy klicu v napovede:
- `obligatory` ... **bold**
- `optional` ... *italic*
- `value_at_*` ... normal

Pripadne neni problem to nejak prohodit. Barvu pozadi bych neupravoval. Ta indikuje, ktery klic je vybrany.
