### ISSUE TITLE
GeoMop - clipboard

### ISSUE THREAD

**Issue by sha512rp** [GeoMop/GeoMop#84]
- [x] prekopirovat pyperclip do common
- [x] odstranit zavislost na gtk, pyqt4
- [x] pod linux zkusit pyqt5, defaultne xclip

**Comment by richtertul** [comment]
Možná to GTK+ bude jediné funkční, tekže spíš ho testnout spustit v try bloku, určitě odstranit pyqt4. Uvidíš.

**Comment by sha512rp** [comment]
- gtk neni pro Python3
- pyqt5 nefungovalo
- xsel mi pri zavolani zamrzlo, nezjistil jsem proc
- defaultne se pro linux pouzije `xclip`, ktery mi jediny fungoval. Pokud neni nainstalovany, schranka funguje, dokud aplikace bezi. Akorat po ukonceni se obsah smaze.

Otestovano pod Windows 10, Linux Mint 17 s `xclip`.
