### ISSUE TITLE
JobScheduler - Direktivy pro PBS file

### ISSUE THREAD

**Issue by johnymachine** [GeoMop/GeoMop#88]
Pro každý systém je to jiné, do budoucna je potřeba nějaký konfigurák pro popis.

**Meta manuál**
# PBS -N mujprvnijob
# PBS -l nodes=1:ppn=1
# PBS -l mem=500mb
# PBS -l scratch=1gb
# PBS -j oe
# PBS -m e

https://wiki.metacentrum.cz/wiki/Jak_za%C4%8D%C3%ADt_po%C4%8D%C3%ADtat_-_tutori%C3%A1l#Specifikace_po.C5.BEadavk.C5.AF_ve_spou.C5.A1t.C4.9Bc.C3.ADm_skriptu

http://docs.adaptivecomputing.com/torque/4-0-2/Content/topics/commands/qsub.htm

**Hydra manuál:** (dokumentace je dost slabá)
-N  #$ -N testjob   jobname to be used in SGE
-M  #$ -M user@domain   sends email notification to user@domain
-m  #$ -m be    mail is to be sent at begin of the job and at the end of the job. use only b for only at beginning of the job or only e for only at the ending of a job
-e  #$ -e /tmp  redirects error file to /tmp
-o  #$ -o ~/out redirects output file to $HOME/out
-q  #$ -q all.q specify queue, i.e. all.q
-cwd    #$ -cwd /home/testuser  execute from the current working directory
-pe #$ -pe openmpi 6    request a parallel environment, i.e. 'openmpi' using 6 slots (CPUs)
-l  #$ -l h_rt=00:30:00 resource request, i.e. 30 minutes run time

http://gridscheduler.sourceforge.net/htmlman/htmlman1/qstat.html

https://service.clustervision.com/content/grid-engine-job-submission

**Zdá se že procesors per node nejde použít na hydře**

**Comment by johnymachine** [comment]
@richtertul Připravil jsem tam prostředí pro to generování, chce to tam pak dopsat to parsování JobId na metacentru a odkomentovat příslušné řádky. Pak to otestují.

Nevím proč, ale z nějakého důvodu mi to pořád padá na hydře, když přidávám cokoliv do těch požadavků, mohl by jsi na to kouknout? 

Za zvážení by stálo možná udělat ta různá prostředí pro komplexnější nastavování než jen zápis do souboru. Možná třeba přesunout i presety enviroments do tohoto modelu...

Každý systém by pak měl nějaké rozhraní které by zpřístupňovalo systémové proměnné, verzi python, cestu k mpi, jazyk toho pbs. atd...

**Comment by richtertul** [comment]
Mě to com.qsub vytvořilo. Když zkusím:
qsub -pe orte 1 js_services/jobs/hydra-localmj/test1/com.qsub
tak to hlásí:
Unable to run job: unknown resource "mem"
V
http://www.fit.vutbr.cz/CVT/cluster/SGE-UsersGuide.pdf
je na str. 44 List of Requestable Attributes, ale není to tam popsaný
