### ISSUE TITLE
Me + Js přidání projektu

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#90]
- [x] v settings přidat workspace
- [x] udělat item project, kde umožnit vybrat, nebo vytvořit nový
- [x] dělat v common, bude společná logika a možná i dialogy
- [x] s projektem se vytvoří prázdný soubor main.yaml 
- [x] pokud bude projekt vybrán, aktuální cesta ksouborům bude workspace + project name, jinak naposledy navštívená
- [x] vhodně zobrazit jméno projektu ve status baru, nebo vedle menu

**Comment by jbrezmorf** [comment]
Předpokládám, že tato nastavení budou do budoucna součástí hlavní aplikace, model editor bude jednou její součástí.

**Comment by richtertul** [comment]
Bud, nebo se bude u všech součástí tahat stejnýma funkcema ze stejného místa. (Proto je to v common)

**Comment by jbrezmorf** [comment]
Mel jsem na mysli uzivatelske rozhrani nikoliv implementaci. V implementaci souhlas, at je to v common.
