### ISSUE TITLE
Me + Js parametry

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#91]
- připravit model editor aby přijímal paramatry ve tvaru ${parameter}
- pokud bude v value ${parameter}, nekontrolovat typ, pokud i něco jiného, musí to být string ( např.:"${parameter}-project")

**Comment by jbrezmorf** [comment]
Tu variantu v řetězci bych neuvažoval, zatím pro to navidím využití a zbytečně by to komplikovalo současnou implementaci.

**Comment by richtertul** [comment]
Nemyslím si že by to komplikovalo implementaci, ale pokud ano, klidně to nedělej.

**Comment by sha512rp** [comment]
Pridano validacni pravidlo pro `${param}` - pri validaci se preskoci.
