### ISSUE TITLE
Me + Js ukládání parametru v projektu

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#92]
- [x] v common udělat ukládání seznamu parametrů a souborů do projektového souboru
- [x] přidat funkce pro vrácení seznamu parametrů a přidání nového, pokud již neexistuje
- [x] použít tyto funke v model editoru po přidání parametru (jen pokud je vybrán project a soubor je v project adresáři), nebo po pro načtení seznamu slov pro našeptávání v případě že je node typu scalar (nebo podle IST je ve value node typu scalar) a je vybrán project
- [x] připravit obecně funkce a v model editoru kontrolovat seznam parametrů a souborů pokud:
  - [x] do projktového adresáře ukládáme soubor
  - [x] z projktového adresáře načítáme soubor

**Comment by jbrezmorf** [comment]
V seznamu parametrů bude vhodné krom jména ukládat i typ jaký parametr nahrazuje, zatím se omezíme na skaláry, ale patrně to nebude do budoucna stačit. Zároveň by to v model editoru umožnilo alespoň elementární kontrolu, že typ sedí, pokud je tejný parametr použit na více místech.

**Comment by richtertul** [comment]
Taky jsem to tak měl rozmyšlený, ale jsou tu dva problémy:
  - autokonverze
  - je tu závislost na ist, která pokud se neuvede v yamlu nemusí být zřejmá  
proto jsem to zatím zadal v této jednoduší variantě.

**Comment by jbrezmorf** [comment]
V principu mame dve moznosti:
1. Ukladat tam jakousi zobecnenou informaci o typu, s tim, ze parametrizovat lze pouze numericke skalary a typy, ktere maji nejaky specialni atribut (to budou zejmena fields), ten atribut by zaroven obsahoval ten zobecneny typ. Analysis by pak pracovala jen s touto mnozinou zobecnenych typu.
2. Ukladat hash typu na miste parametru spolu s odkazem na IST, ktery pri tom byl pouzity.

Lepsi mi prijde varianta 1. jelikoz nam to rovnou bude definovat typy se kterymi musi umet Analysis pracovat.

**Comment by richtertul** [comment]
Tomáši, zatím počítej s tím, že se tam jakýsi typ tahat bude a to jak ve funkcích, tak v souboru. Můžeš ho tam i posílat podle toho co psal Honza v 1.
Podle všeho by informace ist verze měla být v projektovém souboru a ještě na to editor připravit, ale musím to probrat v pondělí s Honzou.

**Comment by sha512rp** [comment]
Ukladani parametru jsem pripravil tak, aby k nim bylo mozne jednoduse pridat typ nebo dalsi dodatecna data.
