### ISSUE TITLE
Me + Js item analyzis

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#93]
V Js přidat item analyzis s subitem create analzyzis, kde se:
  - [x] aktualizují parametry pomocí obecné funkce z common
  - [x] zobrazí se dialog s:
    - [x] s jménem analyzis
    - [x] výběrem yaml souborů (checkbox), defoultně vše vybrané
    - [x] se seznamem parametrů vybraných souborů s možností zadat hodnotu
    - [x] adresář projektu (jen info)
  - [x] po vyplnění vše uložit do projektového adresáře jako name.anal ve formátu json (pro datovou strukturu, ukládání a čtení souboru třídy v common, bede to ve dvou kontextech)
  - [x] pokud bude potvrzen dialog Multijob::add, copy, edit sesynchronizovat vybrané yaml soubory a analyzis s tím co je v   jobs/{mj_name}/mj_conf
  - [x] zkontrolovat že se soubory kopírují, popřípadě opravit communication/installation

**Comment by jbrezmorf** [comment]
Nevidím důvod ukládat konfiguraci analysis jinam než do konfiguračního souboru projektu. Pro zpracování analysis bude myslím lepší posílat celou konfiguraci projektu, protože do budoucna se počítá s možností parametrizovat i geometrii což znamená nutnost mít na výpočetním stroji i různé konfigurace, které nejsou přímo v konfiguraci analysis.

**Comment by richtertul** [comment]
Z toho o čem jsme mluvili v povdělí jsem nabyl dojmu, že projekt může mít více analyzis. To je důvod proč je tu projektový soubor a analyzis. Nebo to bude jinak? Dále se pak kopíruje ta zvolená  tam, kde ji bude číst multijob.

**Comment by jbrezmorf** [comment]
Vice analyzis v projektu jsem neuvazoval, myslel jsem ze by to pak byly samostatne projekty. Leda bychom nejak rozvijeli ten verzovaci pristup z Vistrails.

**Comment by richtertul** [comment]
Uvidíme, zatím bych to takhle nechal a pak se to případně sloučí. Ono je totiž ještě možné, že v projektovém souboru bude něco navíc, co se do analyzis tahat nebude.
