### ISSUE TITLE
Me + Js spouštění flowd

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#94]
- [x] v presetu environments místo sekce Mpi vložit Flow123d s parametry:
  - Flow123d path
  - pbs params (text area s asi 2-3 řádky)
  - command line params (text area s asi 2-3 řádky)
- [x] upravit uložení presetu
- [x] upravit vytváření CommunicatorConfig
  - [x] PbsConfig - přidat text z pbs params jako pole řádků
  -  [x] Flow123d path a command line params (pole řádků) přidat jako vhodné proměnné do CommunicatorConfig
- [x] upravit vytváření proměnné CommunicatorConfig, self.start_job_libs a  self.install_job_libs, nastavit vždy na False a ostatní na None a nechat jak je (v budoucnu se to předělá, jen z adresáře twoparty/install odstarint zip at se to nekopíruje) 
- [x] upravit helpers/pbs aby se při vytváření pbs file přidali pbs params (někam za::

        f.write ('#\n')
        f.write ('\n')

)
- [x] upravit v job.py spouštění jobu, aby se provedli command line params a spustil Flow123d, zatím s 
--version

**Comment by sha512rp** [comment]
Spousteni funguje pres SSH, testovano jako lokalne, tak na hydre (spoustel jsem zkusebni skript, ne flow - ale na tom by nemelo zalezet).

Problem jsem ovsem mel s PBS, prislo mi, ze JS se celkove chova nepredvidatelne pokud jsem se snazil delat neco s PBS. Vetsinou to zamrzlo na installu a zustalo to bezet (musel jsem proces manualne killnout na hydre).

**Comment by richtertul** [comment]
Zkus důsledně před spuštěním mazat adresář js_services na hydře, všechny joby od tebe na pbs qdel -u "user" a killovat tvé spuštěné skripty ps -u "user". To že se to chová nepředvídatelně, ukazuje na toto. 
Pak by se podle logů a připadně podle toho co je potřeba za procesy mazat, měl lokalizovat problém. Kdyžtak mě pošli všechny logy + central log, já se na to podívám. Logy však pro jistotu stahni, nebo porovnej s tím co je na hydře.
Popřípadě se na to podíváme spolu, mohl by jsi zase ve čtvrtek?

**Comment by richtertul** [comment]
Ještě jsem zapoměl, vyzkoušej oba scénáře co by měli fungovat:
app ->(ssh)->delegator->(exec)->js_service->(pbs)->job
app ->(ssh)->delegator->(pbs)->js_service->(ssh)->remote->(pbs)->job
prohlídni i soubory pbs_output a pbs_error v adresáři js_services/jobs/{mj_name}/{job_name}/

**Comment by sha512rp** [comment]
Tak spousteni na PBS se mi uz uspesne ukonci (problem byl v ceste k pythonu a mazani js_services). Akorat ted nevim, jak spoustet flow pres PBS (resp jak job.py odlisit, zda je to spustene pres SSH nebo PBS). Zkusim te zitra zastihnout na Skype, kdyztak muzu dorazit i ve ctvrtek.

**Comment by tomaskrizek** [comment]
Spousteni funguje pro:
app ->(ssh)->delegator->(exec)->js_service->(pbs)->job
app ->(ssh)->delegator->(pbs)->js_service->(ssh)->remote->(pbs)->job

Otestovano vcetne parametru pro CLI a PBS.
