### ISSUE TITLE
Me + Js kopírování výsledků

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#95]
Do Gui přidat tlačítko uložit do záložky results a logs. Ukládat do projektového adresáře / jmeno analyzis / časová značka / log nebo res /

**Comment by tomaskrizek** [comment]
Results i Logs se ukladaji zaroven (jinak byl problem s timestamp), ale udelal jsem to, aby to slo upravit.

Uklada se do `project_dir/analysis/YYYYmmdd_HHMMSS/`. Po ulozeni je mozne slozku otevrit.
