### ISSUE TITLE
Me + Js run analyzis

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#96]
V mj service by měl být kód, který umí přečíst analyzis a spustit vše v jobech. Proto bude nutné zajistit:
  - nakopírování kódu pro čtení analyzis na remote (třida Installation v adr communication)
    - vyresi se pomoci sofistikovanejsiho installu, prozatim kopirovat uz nahrazene analysis
  - nahradit parametry hodnotama
  - jobum předat v parametru jméno souboru s nahrazenýma hodnotama

Rozmyslet a poratit se na řešení, popřípadě, doplním já

**Comment by jbrezmorf** [comment]
Jen upřesnění. Analysis poběží v rámci multijobu, v jobech poběží jdnotlivé instance Flow123d.

**Comment by tomaskrizek** [comment]
Zprovozneno, akorat je potreba doresit spravnou relativni cestu k souborum.
