### ISSUE TITLE
Me + Js installace ssh na windows

### ISSUE THREAD

**Issue by richtertul** [GeoMop/GeoMop#98]
Dořešit installaci ssh na windows
  - jak nainstalovat openSSH a podstrčit dll
  - nakopírovat ssh-ctype do githubu
  - odstranit warning

**Comment by tomaskrizek** [comment]
SSH pod win vyreseno, potreboval to nasledujici dll:
- `libeay32.dll` (OpenSSL)
- `ssh.dll` (libssh, prejmenovano)
- `libgcc_s_dw2-1.dll` (gcc)
- `zlib1.dll`
